### PR TITLE
[13.0] [mig] report qweb pdf watermark

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
@pedrobaeza please review this PR and merge if it is ready.
Thanks in advance.

Regards,

**Comment by pedrobaeza** [comment]
Sorry, I'm not using it.

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Review by dsolanki-initos — APPROVED** [review]

**Pull request merged**
