### PR TITLE
[10.0][report_qweb_pdf_watermark] Fixes on tests and use pyPDF2

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Forward port of past commits made by @hbrunn on the 9.0 branch:
https://github.com/OCA/reporting-engine/commit/c0252f7ce6bec407fcb5eadc814469562f866b7f
https://github.com/OCA/reporting-engine/commit/fcd1117331f8bbd9560d24798ef1aa05fa6acc77

### CODE REVIEW

**Comment by hbrunn** [comment]
any reason not to cherry pick those?

You'll also want to add https://github.com/OCA/reporting-engine/pull/161, because this speeds up the merging by factor 100-1000

**Comment by JordiBForgeFlow** [comment]
OK, will do that then.

**Comment by JordiBForgeFlow** [comment]
@hbrunn I propose to add #161 on a separate PR. This PR is intended to greenify Travis, which now fails in 10.0 due to `report_qweb_pdf_watermark` and `report_qweb_signer`.

@pedrobaeza Travis fails in lint checks on `report_qweb_signer` https://travis-ci.org/OCA/reporting-engine/jobs/275429857#L705, but I think it's an error of lint. The readme.rst repeats some key words.

**Comment by pedrobaeza** [comment]
No, the real error is
```
report_qweb_signer/tests/test_report_qweb_signer.py:9:1: W293 blank line contains whitespace
```
but it's very curious that this didn't raise before... I will check.

**Comment by pedrobaeza** [comment]
You are modifying that file, so it's your error...

**Comment by JordiBForgeFlow** [comment]
Yes, I just fixed the error. The problem is that Travis was stalling due to this module. The root cause is that seems that one can only test PDF reports using HttpCase. Otherwise it stalls. The same happened with `report_qweb_pdf_watermark`.

But not sure why HttpCase works, and others don't. Perhaps @hbrunn knows better.

**Comment by pedrobaeza** [comment]
I think it was @sylvain-garancher who found that problem in OCA/reporting-engine

**Comment by JordiBForgeFlow** [comment]
In any case this PR greenifies Travis for the 10.0 branch. For 9.0 this had already been fixed.

**Comment by JordiBForgeFlow** [comment]
I propose to merge this PR now, as it will greenify the current 10.0 branch, which is failing now and causes all open PR's to fail also.

**Review by pedrobaeza — APPROVED** [review]
OK, fast-tracking

**Review by hbrunn — APPROVED** [review]
agreed, next approval should fast track imho

**Pull request merged**
