### PR TITLE
[16.0] [MIG] report_qweb_pdf_fixed_column: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
standar migration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
AFAIK, this module is not needed in v16.

**Comment by RodrigoBM** [comment]
> AFAIK, this module is not needed in v16.

hi @pedrobaeza 

In the delivery report, I found an error.

In Runboat v16:

Selección_981

In Runboat, this PR:

Selección_980

It is probable that this PR adds a solution, but the fix is in another place.

**Comment by pedrobaeza** [comment]
Uhm, OK, then the problem seems to be the same as previous versions, indeed.

**Comment by RodrigoBM** [comment]
I have tried without my fix, and I have managed to do it by adding the following changes.

Selección_983

Selección_985

Selección_986

and it looks like this in runboat v16

Selección_987


and change other views that inherit from report_delivery_document and propose the change in odoo

**Comment by pedrobaeza** [comment]
Maybe you can propose it to Odoo.

**Comment by RodrigoBM** [comment]
> Maybe you can propose it to Odoo.

i did it @pedrobaeza .

https://github.com/odoo/odoo/pull/172366

**Comment by RodrigoBM** [comment]
Hi @pedrobaeza 

Odoo accepted my PR, I have created these other oca PRs to regularise the inherited views

1. https://github.com/OCA/delivery-carrier/pull/857
2. https://github.com/OCA/delivery-carrier/pull/858
3. https://github.com/OCA/delivery-carrier/pull/859
4. https://github.com/OCA/stock-logistics-reporting/pull/331
5. https://github.com/OCA/stock-logistics-reporting/pull/332
6. https://github.com/OCA/stock-logistics-workflow/pull/1656

I close this PR, thank you very much for your help.

Regards

**Comment by pedrobaeza** [comment]
Thank you for the being so diligent. I have manually update OCB branch with these changes for not waiting till the midnight automation, and fast-tracking the PRs to have everything properly aligned.

As this patch will arrive on v17, can you please check that any possible OCA module is the same aligned?

**Comment by RodrigoBM** [comment]
Yes, I'll try to do that.

**Comment by RodrigoBM** [comment]
Hi @pedrobaeza , 

Change in v17 has already been [merged](https://github.com/odoo/odoo/pull/172741). 

I have checked the current modules and I haven't seen any of them impacted.

 About the modules fixed in V16, there is only one related [PR](https://github.com/OCA/delivery-carrier/pull/769#issuecomment-2243763595) and I have already commented to add the commit to fix the problem.

Best regards

**Comment by pedrobaeza** [comment]
Thanks for the follow up!

**Pull request closed without merging**
