### PR TITLE
[16.0][MIG] report_qweb_pdf_watermark: Migration to 16.0

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Comment by chrisb-c01** [comment]
Can we get this merged?

**Review by antoniocanovas — APPROVED** [review]
Functional review OK

**Review by ConesaJM — APPROVED** [review]
Functional Review Good

**Comment by Jan-Onestein** [comment]
@OCA/reporting-engine-maintainers 

Can we please have this merged ?? :)

**Pull request merged**
