### PR TITLE
[14.0][MIG] report_async

### PR DESCRIPTION
**Pull request by newtratip**
Migrate from https://github.com/OCA/reporting-engine/pull/429

---

**report type as supported**

- qweb-pdf
- qweb-text
- qweb-xml https://github.com/OCA/reporting-engine/tree/14.0/report_xml/
- csv https://github.com/OCA/reporting-engine/pull/511/
- excel https://github.com/OCA/server-tools/tree/14.0/excel_import_export/
- xlsx https://github.com/OCA/reporting-engine/tree/14.0/report_xlsx

@kittiu @atchuthan, Could you please help to review ?

### CODE REVIEW

**Review by atchuthan — APPROVED** [review]
Tested in local with code

**Review by andreampiovesana — APPROVED** [review]
merge?

**Comment by KKamaa** [comment]
@kittiu works well but requires a rebase to current OCA 14.0

**Comment by kittiu** [comment]
@newtratip please rebase.

**Comment by newtratip** [comment]
@kittiu @KKamaa done

**Comment by thomaspaulb** [comment]
Failing tests because of

https://github.com/OCA/server-tools/pull/2317

**Comment by kittiu** [comment]
> Failing tests because of
> 
> [OCA/server-tools#2317](https://github.com/OCA/server-tools/pull/2317)

OK, will wait for that PR to merge first. Thank you.

**Comment by thomaspaulb** [comment]
@kittiu That one got merged, so if you bump/rebuild this it should become green.

**Comment by kittiu** [comment]
@KKamaa @thomaspaulb good to go, now, waiting for the @OCA/reporting-engine-maintainers

**Pull request merged**
