### PR TITLE
10.0 report qweb pdf watermark

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Actual migration in this commit: https://github.com/StefanRijnhart/reporting-engine/commit/58e717a

Only functional change is that I removed the technical settings group tag (i.e. debug mode) on the expression field, because it is not possible to edit reports anyway without entering debug mode in the first place.

cc @hbrunn

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@hbrunn is it a known issue that the watermark is not visible under the text in the report as in this example?

invoices

**Comment by hbrunn** [comment]
@StefanRijnhart no, in 9, this works. Does something set a background here? Or is https://github.com/OCA/OCB/blob/10.0/addons/report/static/src/css/reset.min.css not used for some reason?

**Comment by StefanRijnhart** [comment]
@hbrunn thanks for the pointer! This is actually reproducible on the 9.0 runbot. I'm guessing it's the background: transparent property from that css file that does the trick?

**Comment by StefanRijnhart** [comment]
@hbrunn What a minefield. Probably related to https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2084. Works with wkhtmltopdf 0.12.4 (instead of 0.12.2.4) and loading order of report.assets_pdf.0.css and report.assets_common.0.css reversed (the pdf one last, as it includes the reset CSS).

**Comment by hbrunn** [comment]
nice catch!

**Comment by StefanRijnhart** [comment]
nice module!

**Review by hbrunn — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
Please squash together all "OCA Transbot" commits (https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests)

**Comment by StefanRijnhart** [comment]
@pedrobaeza you got it!

**Review by pedrobaeza — APPROVED** [review]
Thanks! Let's wait for the Odoo's answer before merging this with the hack

**Comment by StefanRijnhart** [comment]
I replaced the workaround for https://github.com/odoo/odoo/issues/16610 with the fix that I also proposed to Odoo as per discussion on the upstream bug.

**Comment by lmignon** [comment]
@pedrobaeza @StefanRijnhart Can we merge this one?

**Comment by StefanRijnhart** [comment]
@lmignon Why, yes!

**Pull request merged**
