### PR TITLE
[13.0] [bi_view_editor] Backport bi_view_editor for Odoo 13

### PR DESCRIPTION
**Pull request by wekeesler**

### CODE REVIEW

**Comment by legalsylvain** [comment]
could you fix pre-commit errors ?

**Comment by wekeesler** [comment]
> could you fix pre-commit errors ?

Fixed!

**Comment by themrwilliams** [comment]
I'd like to use this in 13 as well.  Looking forward to it being merged :)

**Comment by BrandonMehlenbacher** [comment]
I would like to be able to use this on 13.0 as well. Looking forward to an update!

**Pull request closed without merging**
