### PR TITLE
[11.0][MIG] bi_sql_editor

### PR DESCRIPTION
**Pull request by HviorForgeFlow**

### CODE REVIEW

**Review by nicomacr — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Please squash a bit the commit history by author/logical set and I think we are good to go with this PR.

**Comment by nicomacr** [comment]
@hveficent Do you make those changes or can I do them?

**Comment by HviorForgeFlow** [comment]
They are done @nicomacr . I'm working on a error that I caught in production environment. I wish you could help me.
It appears when you try to update bi_sql_editor module and you've already have a materialized view created.

```
Traceback (most recent call last):
  File "/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/odoo/odoo/modules/registry.py", line 306, in init_models
    model._auto_init()
  File "/reporting-engine/bi_sql_editor/models/bi_sql_view.py", line 22, in _auto_init
    return super(BaseModel, self)._auto_init()
  File "/odoo/odoo/models.py", line 2219, in _auto_init
    new = field.update_db(self, columns)
  File "/odoo/odoo/fields.py", line 1944, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/odoo/odoo/fields.py", line 845, in update_db
    self.update_db_column(model, column)
  File "/odoo/odoo/fields.py", line 1947, in update_db_column
    super(Many2one, self).update_db_column(model, column)
  File "/odoo/odoo/fields.py", line 859, in update_db_column
    sql.create_column(model._cr, model._table, self.name, self.column_type[1], self.string)
  File "/odoo/odoo/tools/sql.py", line 77, in create_column
    cr.execute('ALTER TABLE "{}" ADD COLUMN "{}" {}'.format(tablename, columnname, columntype))
  File "/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: "x_bi_sql_view_ddmrp_lt_product" is not a table, composite type, or foreign table
```

**Comment by HviorForgeFlow** [comment]
Still failing when base module is upgraded, upgrade sql_view_editor is possible now, without sending to draft materialized views.

**Review by LoisRForgeFlow — APPROVED** [review]
I can confirm that I can update this module without problem now :+1:  Let's wait for the [Odoo fix](https://github.com/odoo/odoo/pull/26774) to greenify travis and runbot.

**Comment by MiquelRForgeFlow** [comment]
Included cherry-pick of https://github.com/OCA/reporting-engine/pull/239.

**Comment by MiquelRForgeFlow** [comment]
Now this PR is :green_apple: 

@lreficent please, could you functionally review again?

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Thanks @mreficent ! Nice work

**Pull request merged**
