### PR TITLE
[IMP] kpi_dashboard: Allow to set a specific context for a KPI

### PR DESCRIPTION
**Pull request by etobella**
This PR does 2 things. 

- fixes a form
- Allows to add a specific context for a kpi. It is useful in order to use the same kpi for different cases. Only works on compute_on_fly kpi's

### CODE REVIEW

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Comment by etobella** [comment]
Failed due to an update of data. No relation with the PR.

/ocabot merge minor

**Comment by etobella** [comment]
@sbidoul POT Update is failing. Any idea?

**Pull request merged**
