### PR TITLE
[IMP] kpi_dashboard: Allow to set a specific context for a KPI

### PR DESCRIPTION
**Pull request by olgamarcocb**
Adding cherry-pick #575

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Comment by etobella** [comment]
Something is happening with the container. It seems is not being updated:
https://github.com/OCA/oca-ci/runs/6284155668?check_suite_focus=true

@sbidoul

**Pull request merged**
