### PR TITLE
[16.0][IMP] report_csv: support attachment use

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
LGTM

**Comment by ivantodorovich** [comment]
@sbejaoui could you please rebase on top `16.0` ? It seems the merge command failed due to unresolved conflicts

**Comment by sbejaoui** [comment]
> @sbejaoui could you please rebase on top `16.0` ? It seems the merge command failed due to unresolved conflicts

done

**Pull request merged**
