### PR TITLE
[13.0][MIG] report_context

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration to v13 of `report_context`

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by newtratip — APPROVED** [review]
Functional Test : 

I tested pass context language on the report and set `<t t-set="o" t-value="o.with_context(lang=context.get('language'))" />` on qweb view, it's good :+1: 

1. Report with english language
Selection_315
Selection_317

2. Report with thai language
Selection_318
Selection_319

**Comment by etobella** [comment]
@OCA/reporting-engine-maintainers I think this can be merged

**Comment by StefanRijnhart** [comment]
Thanks for the port @jarroyomorales, and thank you @newtratip for the well documented functional test!

/ocabot merge nobump

**Pull request merged**
