### PR TITLE
[MIG] report_substitute: Migration to 13.0

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by gurneyalex** [comment]
Hello @jjscarafia you should configure pre-commit as explained in https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

**Comment by jjscarafia** [comment]
hi @gurneyalex 
Thanks for taking care of it.
I've installed and run pre-commit, but I didn't find a way to fix [this line](https://github.com/OCA/reporting-engine/pull/424/files#diff-4658b1389f60cdfe95a7c0f9a8006f21R26)
I've tried different approaches but the line is re-formated by "black" and then gives an error by "flake8"

Do you know a proper way to code that line?
Thanks!

**Comment by gurneyalex** [comment]
@jjscarafia Try this:

```
diff --git a/report_substitute/wizards/mail_compose_message.py b/report_substitute/wizards/mail_compose_message.py
index 9c7932e65..b488265c3 100644
--- a/report_substitute/wizards/mail_compose_message.py
+++ b/report_substitute/wizards/mail_compose_message.py
@@ -22,13 +22,12 @@ class MailComposeMessage(models.TransientModel):
                 and report_template.action_report_substitution_rule_ids
                 and active_ids
             ):
-                old_report_template = report_template
-                self.template_id.report_template = old_report_template.get_substitution_report(
-                    active_ids
-                )
+                old_template = report_template
+                updated_template = old_template.get_substitution_report(active_ids)
+                self.template_id.report_template = updated_template
                 onchange_result_with_substituted_report = (
                     super().onchange_template_id_wrapper()
                 )
-                self.template_id.report_template = old_report_template
+                self.template_id.report_template = old_template
                 return onchange_result_with_substituted_report
         return super().onchange_template_id_wrapper()

```

**Comment by sbejaoui** [comment]
I fixed travis in #453

**Comment by jjscarafia** [comment]
close in favor of https://github.com/OCA/reporting-engine/pull/453

**Pull request closed without merging**
