### PR TITLE
[MIG] report_csv: Migration to 16.0

### PR DESCRIPTION
**Pull request by AnizR**

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
Thanks @AnizR !

**Review by bealdav — APPROVED** [review]
Test in module OK. Thanks

**Review by andreampiovesana — APPROVED** [review]
LGTM
functional test ok

**Comment by BT-anieto** [comment]
@AnizR Thank you for your contribution! Could you increase the test coverage so that it can be merged? Could you add this module to the v16 issues so that it is clear that it is being migrated? Thank you!

/ocabot migration report_csv

**Comment by adrienpeiffer** [comment]
@OCA/reporting-engine-maintainers Is it possible to merge this one ?

**Pull request closed without merging**
