### PR TITLE
[FIX] report_xml: add context to /report/download

### PR DESCRIPTION
**Pull request by gaikaz**
Odoo did this change in [this commit](https://github.com/odoo/odoo/commit/4c9624db9d4656457f4100ee2e848f0f81d264a9)

### CODE REVIEW

**Review by DonatasV — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM

By the way, you proposed the change for 13.0 and showed the commit from 14.0. However, this is already present on 13 :wink: 
https://github.com/odoo/odoo/blob/13.0/addons/web/controllers/main.py#L2010

**Comment by gaikaz** [comment]
@etobella I'm pretty sure this is just GitHub showing the newest branch on the commit 😛 
I think the commit is the same since then.

**Comment by gaikaz** [comment]
Dear Maintainers, could we merge this 🙏🏻

**Review by Du-ma — APPROVED** [review]
Nice :rooster: !

**Comment by Du-ma** [comment]
:sleeping_bed: :sleeping:

**Comment by etobella** [comment]
@OCA/reporting-engine-maintainers Can you merge this please?

**Pull request merged**
