### PR TITLE
[MIG] report_qweb_encrypt: Migration to 15.0

### PR DESCRIPTION
**Pull request by grzana12**

### CODE REVIEW

**Comment by grzana12** [comment]
@kittiu could you approve and merge?

**Comment by bosd** [comment]
@grzana12 Can you squash commits?
Please attend to version bump, it should be `15.0.1.0.0`

**Comment by kittiu** [comment]
Ping @TheerayutEncoder @Saran440 can you help review this? Thnaks.

**Comment by grzana12** [comment]
> @grzana12 Can you squash commits? Please attend to version bump, it should be `15.0.1.0.0`

@bosd ready

**Comment by bosd** [comment]
@grzana12 Thanks for your efforts and very quick response.
You have squashed a bit to much. A bit of the history is lost now. Such as the migration commits of V14.
(Only your last commits should have been sqaushed in the `[MIG] report_qweb_encrypt: Migration to 15.0`.)

Please refer to the migration guide:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by grzana12** [comment]
@bosd oh sorry. I will prepare new branch with that changes.

**Comment by grzana12** [comment]
New PR created #681

**Pull request closed without merging**
