### PR TITLE
[14.0][FIX] report_xml

### PR DESCRIPTION
**Pull request by Du-ma**
Passing `context`, and taking `safe_eval` from where it's supposed to be taken from.
Also passing `time` from `safe_eval` to report name, because why not?

[](http://www.youtube.com/watch?v=Ciw-almypOU "Video Title")

### CODE REVIEW

**Comment by Du-ma** [comment]
Also a thing to mention, the `context` thing was actually fixed on 13.0 #489 but, during the migration to 14.0 #514 it, together with `time` param, vanished :smile:

**Comment by Du-ma** [comment]
@etobella @ozono 
Check this out lads

**Review by ozono — APPROVED** [review]
LGTM. Well done.

**Comment by Du-ma** [comment]
@OCA/reporting-engine-maintainers 
Could this be looked at? This module isn't in a working state without this fix :smile:

**Comment by pedrobaeza** [comment]
Is it safe eval strictly needed?

**Comment by etobella** [comment]
It is used for attachment name, the same logic applied on odoo:
https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_actions_report.py#L202

**Review by etobella — APPROVED** [review]

**Pull request merged**
