### PR TITLE
[ADD] report csv

### PR DESCRIPTION
**Pull request by etobella**
This module allows to create csv reports directly on odoo on a similar way than `report_xlsx`

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@alexis-via didn't you develop something similar?

**Comment by alexis-via** [comment]
@pedrobaeza Maybe report_qweb_txt https://github.com/OCA/reporting-engine/tree/10.0/report_qweb_txt

**Comment by pedrobaeza** [comment]
Yeah, that's the one I remember. It's not the same then.

**Review by JordiBForgeFlow — APPROVED** [review]
Code review and functional tests

**Review by LoisRForgeFlow — APPROVED** [review]
Great module! :+1:

**Review by jarroyomorales — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
The problem I see with this module (and the `report_xlsx` one) is the need of adding code for using it, instead of using data for generating reports. On `report_xml`, a data file serves as "template" for generating the XML. I know it's not the same target, but maybe there's some way of doing this in a similar manner.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza I think that it's convinient for some use cases. And for some others it won't. I see that the module is formally correct, and solves a use case.

**Comment by etobella** [comment]
If we want to make the CSV from the XML we should create a parser and define the logic somewhere. It shouldn't be hard, but I think it is out of the scope of this module. Maybe, I could create an upgrade after this module. What do you think @pedrobaeza ?

**Comment by pedrobaeza** [comment]
Yes, I'm not blocking this. Simply thinking out loud for a better design.

**Pull request merged**
