### PR TITLE
[13.0][MIG] bi_view_editor

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by isdabenx** [comment]
is there a problem? I see that it has not yet been definitively ported to version 13.

**Comment by astirpe** [comment]
@isdabenx we need another review in order to merge this PR. Would you like to make your review here?

**Comment by IssamMaamria** [comment]
Hi guys - what is outstanding for this to be complete?

**Comment by astirpe** [comment]
@IssamMaamria  we need another review in order to merge this PR. Would you like to make your review here?

**Comment by IssamMaamria** [comment]
Has this been tested?

We will be testing this on our side and report back

**Comment by astirpe** [comment]
Thanks @IssamMaamria ! Very appreciated!

**Pull request closed without merging**
