### PR TITLE
[11.0][MIG] report_py3o (Work in Progress)

### PR DESCRIPTION
**Pull request by BT-nfrei**
Hello everyone,
This PR is just a starting point for the migration of this module. At brain-tec, we like this module and we will contribute to its migration to 11.0.
After looking at the technical implementation in 10.0, we still have some doubts about the parser part (report_sxw/rml_parse, contexts). So it would be nice to get some inputs from the initial creators like @lmignon, @alexis-via or @guewen.
In 11.0, it seems quite clear that we have to move away from the SXW/RML technology. So I'm not sure if we should try to keep as much as possible from the current implementation or maybe get some inspiration from report_xlsx which is already migrated to 11.0.
So if you have inputs or advice, please let us know.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests, and maybe some others by logical set/author.

**Comment by lmignon** [comment]
@BT-nfrei You're welcome to migrate this module.  I have not yet had the opportunity to look in detail at the implementation of V11 reports and V10 changes but it seems to me that the way to go would be as follows...

To declare our py3o report, we just need to inherit from `ir.actions.report`, add `py3o`into the `report_type` selection, implement the method `render_py3o` and override `_get_report_from_name`

```python
from odoo import api, fields, models, _
from odoo.exceptions import UserError


class ReportAction(models.Model):
    _inherit = 'ir.actions.report'

    report_type = fields.Selection(selection_add=[("py3o", "py3o")])

    @api.model
    def render_py3o(self, docids, data):
        ....

    @api.model
    def _get_report_from_name(self, report_name):
        res = super(ReportAction, self)._get_report_from_name(report_name)
        if res:
            return res
        report_obj = self.env['ir.actions.report']
        qwebtypes = ['py3o']
        conditions = [('report_type', 'in', qwebtypes),
                      ('report_name', '=', report_name)]
        context = self.env['res.users'].context_get()
        return report_obj.with_context(context).search(conditions, limit=1)
```
You should also move all the fields from https://github.com/OCA/reporting-engine/blob/10.0/report_py3o/models/ir_actions_report_xml.py into `ReportAction`

We can keep the implementation of the logic to render the report into the wizard as it's done in 10.0 https://github.com/OCA/reporting-engine/blob/10.0/report_py3o/models/py3o_report.py#L83
All you need to do is to replace the field `ir_actions_report_xml_id` by `ir_actions_report_id`

By keeping the wizard we ease the maintenance of this module across versions and the implementation of `render_py3o` could look like

```python
    @api.model
    def render_py3o(self, docids, data):
        report = self.get_report_from_name(self.report_name)
        return self.env['py3o.report'].create({
                'ir_actions_report_id': report.id
         }).create_report(res_ids, data)
```

**Comment by ghost** [comment]
Good morning all,

I am the man who is helping Nicolas to migrate the py3o module and we have some problems with it.

Following @lmignon 's answer we found that:

- `rml_parse` has dissapeared in odoo11, but well we could take it from `10.0`.
- `cStringIO` is not used more in `python3.5` so we could not use `StringIO`, another posibility is that we could use from `io` the streams `BytesIO` and `StringIO` but there are some differences between both `StringIO` libraries https://stackoverflow.com/a/49795277.

I keep researching it, so I will add some more information about it.

**Comment by ghost** [comment]
Adding information to the comment above:

There is some fields values from `res.company` required in `rml_parse` that in version 11.0 have dissapeared, they are related to rml_report: `rml_header1, rml_header2, rml_header3...`
[res.company v10.0](https://github.com/OCA/OCB/blob/d46aabe0ece0f9814db2dd0fa07c322c1fca0eb1/odoo/addons/base/res/res_company.py#L137-L140)
   ```python
 rml_header = fields.Text(required=True, default=_get_header)
 rml_header1 = fields.Char(string='Company Tagline', help="Appears by default on the top right corner of your printed documents (report header).")
 rml_header2 = fields.Text(string='RML Internal Header', required=True, default=_header2)
 rml_header3 = fields.Text(string='RML Internal Header for Landscape Reports', required=True, default=_header3)
```

**Comment by ghost** [comment]
More information about the migration:

There is an error in the py3o.template library that produces an exception in the Genshi call:
`File "/usr/local/lib/python3.5/dist-packages/genshi/template/astutil.py", line 91, in visit 
      ret = visitor(node)
File "/usr/local/lib/python3.5/dist-packages/genshi/template/astutil.py", line 104, in visit_Expression
      return self.visit(node.body)
File "/usr/local/lib/python3.5/dist-packages/genshi/template/astutil.py", line 90, in visit
      raise Exception('Unhandled node type %r' % type(node))`
**Exception: Unhandled node type <class '_ast.NameConstant'>**

I have researched about it, it has a fix in the _version 0.7.x_ but there is not a updated release inside [Pypi](https://pypi.org/project/Genshi/)) so we need to upgrade manually from [Genshi 0.7.x](https://github.com/edgewall/genshi/tree/stable/0.7.x)

Uninstall previous Genshi -> Clone repo -> Install (**_$ python3.5 setup.py install_**)

**Comment by bennals** [comment]
@BT-ccebrian Any update on the migration of this module?  I'm stuck in v11 community with an imminent need to do some report customisation (not good planning on my part...my bad) and this module seems the best fit/closest to migration.  Is it's current state not functional at all or can it be installed with some workarounds and used in sub-optimal/buggy-but-not-show-stopping ways as I'd be prepared to put up with some trouble along the way?  Happy to consider financial contribution as well as my only option seems to be learning QWeb (lot of time and effort for a non-developer).

**Comment by tansadio** [comment]
Hi @BT-ccebrian, 

Have you migrate the py3o_server file ?  Or have you planned to add this on your PR ?
Otherwise, I can add it.
Thanks in advance.

**Comment by ghost** [comment]
Hi @bennals, we are currently working on the migration, we made as you said a sub-optimal version but not supported from our side, the version in 10.0 is not working on 11.0 because of RML parser is not working anymore, of course we will not benefit from any contribution in no way so we could contact each other or send an email to our company for getting closer and talk about it.

Hi @tansadio we have not touched this module, our scope was only for the py3o report, so feel free to work around it.

**Comment by ghost** [comment]
@bennals @tansadio 
I apologize for the delay in the replies.

**Comment by gmarczynski-ira** [comment]
Hi @BT-ccebrian, I checked your migration and it works (including unit tests) only after installing Geneshi 0.8 for Python 3.5+ https://github.com/lelit/genshi/tree/3.5+ 
And also one needs to remove `.encode('utf-8')` at `report_sxw.py:264`.
Thanks!

**Comment by lmignon** [comment]
@BT-ccebrian Can you squash the commits related to the migration into one to ease the review. Thank you!

**Comment by alexis-via** [comment]
It's certainly not fun to do, but it would be great to get the latest improvements from v10, in particular the support for PDF export options (https://github.com/OCA/reporting-engine/pull/211).

**Comment by ghost** [comment]
Good morning @gmarczynski-ira @lmignon @alexis-via, thank you for the feedback, I will take some time for making the changes and for getting closer to the merge. As soon as I have the version updated I will comment the thread.

Thank you!

**Comment by gmarczynski-ira** [comment]
@BT-ccebrian after some more tests I find that the document merging does not work (neither for PDF nor for ODT). I will let you know if I find a solution for that.

**Comment by njeudy** [comment]
@BT-ccebrian any news on this ?

**Comment by ghost** [comment]
Hi @all I have received news from above, we reached that this is a low-priority task for us.
Feel free for taking the migration task!

Thank you very much,
Best regards.

**Comment by lmignon** [comment]
@BT-ccebrian I have to migrate this addon to V12. The first step is therefore to finalise the migration in V11. The commit history is a little bit ugly.  Can I rewrite your commits to group all your changes into one ? I'll preserve the authorship.
Regards,

lmi

**Comment by bennals** [comment]
@lmignon Do the decisions you've made about migrating this module to V12 mean that migrating it to V11 will be bypassed (for now at least)?

**Comment by lmignon** [comment]
@bennals IMO you can take the code from #238, change the version into the manifest and that should work as is in V11. I've finally based the migration on the latest changes into V10.

**Comment by bennals** [comment]
@lmignon ok, thanks, but should that be #258 rather than #238

**Comment by lmignon** [comment]
@bennals Yes it's #258 rather than #238

**Comment by bennals** [comment]
thanks!

**Comment by abdelhamid-attaby** [comment]
Hi everyone, this work is really amazing. Can I know the progress of this migration and what is the expected time to be migrated to V12.0 ?

**Comment by tbaden** [comment]
is anybody working on this?
otherwise I think it would be quicker to backport the v12 migration https://github.com/OCA/reporting-engine/pull/258

**Comment by tbaden** [comment]
opened a new PR for this migration: https://github.com/OCA/reporting-engine/pull/285 
I'm grateful for any help.

**Comment by lmignon** [comment]
@tbaden Indeed, it should be easier and quicker to backport chanegs from V12. I close this one.

**Pull request closed without merging**
