### PR TITLE
[MIG] Migration of report_xlsx to 10.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by lmignon** [comment]
@moylop260 Travis fails with a false negative... The check for the use of new api must not be applied to python classes that don't inherit from base.model.....  https://github.com/odoo/odoo/blob/10.0/odoo/report/report_sxw.py#L329

**Review by lmignon — CHANGES_REQUESTED** [review]
We need to find a way to ignore the travis error...Can you declare PYLINT_EXPECTED_ERRORS=1 in the env matrix in .travis.yml

**Comment by pedrobaeza** [comment]
That's a warning, not an error. The error is:

```
report_xlsx/__manifest__.py:4: [W0109(duplicate-key), ] Duplicate key 'installable' in dictionary
```

**Review by pedrobaeza — APPROVED** [review]
Squashing the commits on merge

**Review by lmignon — APPROVED** [review]
@pedrobaeza you're right...

**Review by alexis-via — APPROVED** [review]

**Comment by sbidoul** [comment]
@adrienpeiffer please update the runbot link branch in the readme.

**Comment by adrienpeiffer** [comment]
Thanks @sbidoul !

**Pull request merged**
