### PR TITLE
[12.0][MIG] bi_sql_editor

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Migration of module bi_sql_editor to v12

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@ageficent Please, cherry-pick (and adapt) the commit of https://github.com/OCA/reporting-engine/pull/269.

**Comment by AdriaGForgeFlow** [comment]
> @ageficent Please, cherry-pick (and adapt) the commit of #269.

Done :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test OK. LGTM.

**Comment by CasVissers-360ERP** [comment]
@ageficent 
I do get this error again on update all:
psycopg2.ProgrammingError: "x_bi_sql_view_xx" is not a table, composite type, or foreign table

I believe this was fixed in v11 version.

**Comment by MiquelRForgeFlow** [comment]
@CasVissers See https://github.com/OCA/reporting-engine/blob/12.0/bi_sql_editor/readme/INSTALL.rst

**Comment by CasVissers-360ERP** [comment]
@mreficent 👍

**Pull request merged**
