### PR TITLE
[MIG][9.0] report qweb element page visibility

### PR DESCRIPTION
**Pull request by SodexisTeam**
Module ported from 8.0 to 9.0 with minor changes to it.

cc: @hurrinico

### CODE REVIEW

**Comment by hurrinico** [comment]
LGTM 👍  Thank you @SodexisTeam

**Comment by pedrobaeza** [comment]
There's already a PR for this: https://github.com/OCA/reporting-engine/pull/54

**Comment by atchuthan** [comment]
@pedrobaeza I started with this work after I tested whether there was any work in the list of to do at https://github.com/OCA/reporting-engine/issues/27.

**Comment by pedrobaeza** [comment]
Yeah, sorry for not annotating it, but it should be auto-reported, because I can't control everything.

**Comment by atchuthan** [comment]
@pedrobaeza ok.

https://github.com/OCA/reporting-engine/pull/54 seems to have no activity since June 1 and still remains in "needs fixing" label.

So, how does OCA work in these cases?  or should I cancel this PR to avoid duplicate work?

**Comment by pedrobaeza** [comment]
You can write this person to see if there's interest. If yes, you can make PR over his branch. If not, we close that PR and use yours, but seeing if there's something in their branch interesting for merging in yours.

**Comment by atchuthan** [comment]
we are closing this PR as similar PR https://github.com/OCA/reporting-engine/pull/71 has been fixed.

**Pull request closed without merging**
