### PR TITLE
[IMP] kpi_dashboard: new widgets & edit context items

### PR DESCRIPTION
**Pull request by etobella**
This PR will allow:
- [x] Create widget integer
- [x] Create widget counter
- [x] Allow buttons to edit context and pass it to on fly kpis
- [x] Allow to edit color of the element using context

### CODE REVIEW

**Comment by etobella** [comment]
This is how it works :smile: 
dashboard_js_ctx

**Review by legalsylvain — APPROVED** [review]
Lgtm, thanks !
Cose review, no test.

One question : I dont see the use case for modifying values, clicking on a item, could you give an example ?

**Comment by etobella** [comment]
I want to modify the context and with the compute_on_fly we could create some knids of selectors. For example:
When you open the dashboard you see yesterday sale orders, but you could select  all the week, all the month, etc.

**Comment by etobella** [comment]
Maybe this example is better
peek selector

**Comment by gurneyalex** [comment]
Hello I see an uncheced item in the list, is this still being worked on? If so maybe you can set it to draft.

**Comment by etobella** [comment]
@gurneyalex All the items were implemented. I just forgot to check the button :facepalm:. I just remove a console.log item now

**Review by jarroyomorales — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
