### PR TITLE
[15.0][MIG] kpi_dashboard

### PR DESCRIPTION
**Pull request by brian10048**
replace #570 due to inactivity

### CODE REVIEW

**Comment by brian10048** [comment]
ready for review @etobella

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@etobella Can you review/test please?

**Comment by etobella** [comment]
Same comment than previous PR Applies: https://github.com/OCA/reporting-engine/pull/570#issuecomment-1127805768

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
