### PR TITLE
[FIX] report_xlsx running report in su mode

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**
#586 
problem explained in the issue

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
This imitates what Odoo [does](https://github.com/odoo/odoo/blob/4c403cb87a0c6e88795231e4ba77935771474aaa/odoo/addons/base/models/ir_actions_report.py#L876).

**Comment by sbidoul** [comment]
@luc-demeyer you may be interested in this fix.

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by sbidoul** [comment]
Note this may have backward compatibility implication if people have reports that relied accidentally on running as sudo. But this has to be fixed.

This bug appeared in v14, where Odoo added a sudo() in `_get_report_from_name()`. So v13 is ok. This will have to be ported to v15.

**Comment by pedrobaeza** [comment]
Please fw-port it to v15:

/ocabot merge patch

**Pull request merged**
