### PR TITLE
[12.0][IMP] report_xlsx, make sure print_report_name works

### PR DESCRIPTION
**Pull request by kittiu**
This improve make sure `print_report_name` field in report action will works, as it not work previously.

Note: do I need to set minor version to 12.0.1.0.1 ? Is it updated auto by Bot?

### CODE REVIEW

**Comment by jffernandez** [comment]
Will it be merged? Thank you!

**Comment by pedrobaeza** [comment]
@jffernandez start approving this PR

https://odoo-community.org/page/review

**Comment by jffernandez** [comment]
Oh! I don't knew that I could approve pull requests! Thank you, @pedrobaeza 
On it!

**Review by jffernandez — APPROVED** [review]
Generated a partner XLSX with the print_report_name='Partner %s' % (object.name)
Works as expected. Nice work!
(Can it be cherry picked to v.11 on merge? TY)

**Comment by kittiu** [comment]
What is cheery pick? I can migrate to v11 once this is merged!?

**Comment by pedrobaeza** [comment]
@kittiu it's a comfortable way of applying one commit in other branch:

https://git-scm.com/docs/git-cherry-pick

Merging this now. You can cherry-pick and do the PR, or redo the diff for v11 and do the PR.

/ocabot merge patch

**Pull request merged**
