### PR TITLE
[16.0][MIG] sql_export_mail (from OCA/server-tools 14.0)

### PR DESCRIPTION
**Pull request by legalsylvain**
simple PR

- Update views, regarding changes in sql_export module
- Add prepare function for cron vals

depends on #671, #669

### CODE REVIEW

**Comment by florian-dacosta** [comment]
@legalsylvain can you rebase please?

**Comment by florian-dacosta** [comment]
@legalsylvain Rebase did not work, could you do it without oca bot ?
Thanks !

**Comment by legalsylvain** [comment]
Done.
CI looks green.

**Review by florian-dacosta — APPROVED** [review]

**Review by bealdav — APPROVED** [review]
LGTM

**Pull request merged**
