### PR TITLE
10.0 del report custom filename

### PR DESCRIPTION
**Pull request by mourad-ehm**
This feature is in 10. 
 Field: Printed Report Name 
ex for sale order: ( object.state in ('draft','sent') and 'Quotation' or 'Sale') + object.name +'.pdf'

### CODE REVIEW

**Comment by dreispt** [comment]
I wish the removal commit message were more explicit: in the feature people that want to know why it was removed will try to refer to it.

**Comment by mourad-ehm** [comment]
@dreispt , what do you think about this commit message:  [DEL] module report_custom_filename: feature is already in odoo 10.0

**Comment by dreispt** [comment]
Sounds good.

**Review by StefanRijnhart — APPROVED** [review]
Thanks! Is it necessary to take the updates to this module from the previous branch before deleting the module?

**Review by pedrobaeza — APPROVED** [review]
Squashing on merge solves the problem!

**Pull request merged**
