### PR TITLE
[13.0][MIG] report xlsx migration to v13

### PR DESCRIPTION
**Pull request by schout-it**

### CODE REVIEW

**Comment by etobella** [comment]
I have tried to make it work on runbot, but it leaves some JS errors

**Comment by dynapps** [comment]
@etobella could you tell me where?
if I try the runbot, go to partners, select list view and click the export all (download icon)
it seems to work without problem.
This is for the v13
In this migration I included a javascript fix that should probably be backported to v12

**Comment by sbidoul** [comment]
@schout-it could you rebase to get the new linters, and apply `pre-commit run -a` in a separate commit?

**Comment by kongrattapong** [comment]
It's seem it's still not working.
I go to partner then "Print to XLSX" but it's not export .xlsx file
xlsx_report

**Comment by JoanSForgeFlow** [comment]
Please, if possible, review my PR [(schout/reporting-engine)](https://github.com/schout-it/reporting-engine/pull/1) that fixes the module.

**Comment by schout-it** [comment]
Done

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review :+1:

**Comment by JoanSForgeFlow** [comment]
Thank you @schout-it !

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
