### PR TITLE
[17.0][MIG] report_qweb_parameter: Migration to 17.0 

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Comment by ramiadavid** [comment]
@OCA/community-maintainers Tests and runboat are not working in this repository

**Comment by dreispt** [comment]
The manifest version needs to be changed to 17.0.
Don't remove the utf8 encoding tag from the XML file please.

**Comment by ramiadavid** [comment]
@dreispt 
It's true that I missed the version change, but didn't this warn pre-commit previously?
utf8 encoding tag is deprecated in v17

`DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, can just have a UTF8 description with not need for a declaration.`

**Comment by ramiadavid** [comment]
@dreispt Sorry, I didn't understand it well, it's only for HTML, not XML, I've already added it again.

**Pull request merged**
