### PR TITLE
[16.0][MIG] report_qweb_element_page_visibility: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-atornero**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Comment by chrisb-c01** [comment]
I tested this PR locally but was unable to get it to work. When debugging I figured out it is because the `let`'s in the JS code (layout.xml) are not handled well by wkhtmltopdf (0.12.6). I changed them to `var`'s and now its working.

Also there is a duplicate PR [here](https://github.com/OCA/reporting-engine/pull/704).

The error I got (needed to enable JS debugging in the wkhtmltopdf command):

```
Warning: undefined:0 ReferenceError: Can't find variable: subst   
```

**Comment by HviorForgeFlow** [comment]
Could you apply https://github.com/OCA/reporting-engine/pull/540

**Review by nguyenminhchien — CHANGES_REQUESTED** [review]
I face the same problem with @chrisb-c01 .
please replace `let` by `var`

**Review by nguyenminhchien — APPROVED** [review]
lgtm

**Comment by HviorForgeFlow** [comment]
@BT-atornero could you squash https://github.com/OCA/reporting-engine/pull/713/commits/61fa31191838db3cd0c815858eb2204dd6a34996 and https://github.com/OCA/reporting-engine/pull/713/commits/3a29e7738df8afebc87156b387818aef7dd57413?
Also cherry-pick the original https://github.com/OCA/reporting-engine/pull/713/commits/fe015960335504c2da4c2aa097ec4de438b1be7e to keep commit authorship?
Code review :+1:

**Comment by BT-atornero** [comment]
@HviorForgeFlow done, thank you for the review :)

**Pull request merged**
