### PR TITLE
[MIG] report_qweb_encrypt: Migration to 15.0

### PR DESCRIPTION
**Pull request by grzana12**

### CODE REVIEW

**Comment by grzana12** [comment]
@bosd now it should be fine :D

**Review by bosd — APPROVED** [review]
Quick code review, based on previous pr. LGTM :+1
Commit history looks good now!
Thanks for your contribution!

**Comment by TheerayutEncoder** [comment]
Excuse me, I tested this on odoo v15.
After I go to **Settings > Technical > Reporting > Reports**
And I edited Reports/Invoices encryption as **Manual Input Password** then save
So I tried to print invoice report and error occurred

Please check your code.
Thanks.

This is an error 
`UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'call')
TypeError: Cannot read properties of undefined (reading 'call')
    at QWeb.eval (eval at _compile (http://localhost:15069/web/assets/409-7a8a4d9/web.assets_common.min.js:1014:178), <anonymous>:77:44)
    at QWeb.render (http://localhost:15069/web/assets/409-7a8a4d9/web.assets_common.min.js:1005:20)
    at EncryptDialog.__render (http://localhost:15069/web/assets/409-7a8a4d9/web.assets_common.min.js:1332:33)
    at EncryptDialog.__prepareAndRender (http://localhost:15069/web/assets/409-7a8a4d9/web.assets_common.min.js:1330:29)`

**Pull request merged**
