### PR TITLE
[FIX] [16.0] report_display_name_in_footer: Param with noupdate

### PR DESCRIPTION
**Pull request by Shide**
Add noupdate=1 on parameter

Added roadmap/issues to readme to explain some and unusual special case.

MT-5999 @moduon @Gelojr @fcvalgar @yajo @rafaelbn please review if you want :)

### CODE REVIEW

**Review by EmilioPascual — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍🏼

**Review by fcvalgar — APPROVED** [review]

**Review by Gelojr — APPROVED** [review]
LGTM Nice @Shide

**Pull request merged**
