### PR TITLE
[16.0][FIX] email template on sql_export_mail

### PR DESCRIPTION
**Pull request by florian-dacosta**
@legalsylvain

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Nice catch ! 
could you provide also the migration script ?

**Comment by florian-dacosta** [comment]
> Nice catch ! could you provide also the migration script ?

It  seems quite complicated since the mail template can be customized by every customer, I can't juste replace the old template content by the new one.
I'd have to keep old content but replace the variables with a regex or something ?

**Comment by legalsylvain** [comment]
> It seems quite complicated since the mail template can be customized by every customer, I can't juste replace the old template content by the new one.

Hi. For that topic, the postulate of openupgrade is the following : 
A) if we don't do anything, all the templates will fail. (because the syntax changed) and user should set again all the values 
B) if we erase the ``email_to``, ``subject`` and ``email_to``, it will work, but the customized values (if any) will be lost and should be set again. (or default value will be used).

The B situation is better than the A situation.
So in Openugprade, we assume loosing "now bad" values for records set as noupdate="1".

See exemple here : 
- the noupdate.xml file for a mail.template : https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_scripts/scripts/purchase/15.0.1.2/noupdate_changes.xml#L3
- the call to the load of the noupdate.xml file in a post-migration.py file : https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_scripts/scripts/purchase/15.0.1.2/post-migration.py#L13

**Comment by florian-dacosta** [comment]
@legalsylvain Thanks for the hint, I've added a migration script.
I've put it for 16.0.1.0.0 version assuming we don't want to play this migration script on some instance with v16 module already installed, as we can assume they already fixed the template themselve and don't want to erase it in this case.

**Comment by legalsylvain** [comment]
Thanks ! 

/ocabot merge patch

**Pull request merged**
