### PR TITLE
[17.0][MIG] report_qweb_element_page_visibility

### PR DESCRIPTION
**Pull request by sanderlienaerts**

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]

**Comment by sanderlienaerts** [comment]
@gurneyalex this one as well, thanks!

**Review by hildickethan — APPROVED** [review]

**Comment by altela** [comment]
any info when is this going to be merged? great work thx

edit : typo

**Review by FernandoRomera — APPROVED** [review]
LGTM

**Pull request merged**
