### PR TITLE
[14.0] [MIG] Migrate module report_wkhtmltopdf_param to v14

### PR DESCRIPTION
**Pull request by fshah-initos**
[14.0] [MIG] Migrate module report_wkhtmltopdf_param to v14

### CODE REVIEW

**Comment by fshah-initos** [comment]
@mlaitinen This branch is all set to review v14 migrated module `report_wkhtmltopdf_param`
Please check and let me know your feedback.

**Review by broeking — APPROVED** [review]

**Review by broeking — APPROVED** [review]

**Comment by mlaitinen** [comment]
I'm a little bit confused about the dotfiles in the diff. They seem to be in `14.0` as well, but they still show up as a change. Are they supposed to?

**Comment by mlaitinen** [comment]
I have a feeling that 22c7047808ff15a513a66e67adb8039a524a1407 doesn't belong to this PR. I could be wrong though.

**Comment by foramaktiv** [comment]
@mlaitinen I have fixed all suggested changes. Could you please make another review?

Thanks in advance.

**Comment by fshah-initos** [comment]
@mlaitinen I have fixed all suggested changes. Could you please review it.
Thanks in advance!

**Comment by fshah-initos** [comment]
@Saran440 will you please review the migration for v14.
Thanks!

**Comment by fshah-initos** [comment]
@all can anyone please review this?

**Comment by fshah-initos** [comment]
@etobella Is it possible to review this PR ?

**Review by Saran440 — APPROVED** [review]
Code is not changed. :+1:

**Comment by fshah-initos** [comment]
@alexis-via Is it possible to merge this PR as it approved.
Thanks in Advance!

**Comment by fshah-initos** [comment]
@OCA/reporting-engine-maintainers can you please merge this PR as it is approved.
Thanks in advance!

**Comment by fshah-initos** [comment]
@all can someone please merge this PR?

**Comment by fshah-initos** [comment]
It would be great if somone could merge this PR. we need to merge this ASAP.

**Comment by fshah-initos** [comment]
It would be great if we could merge the PR

**Comment by mlaitinen** [comment]
No idea if anyone can do that but let's give it a shot..

**Pull request merged**
