### PR TITLE
[FIX] report_py3o: fix onchange

### PR DESCRIPTION
**Pull request by etobella**
When changing the type in order to select the configuration an error was raised, as the format_type was not defined. Now it works as expected

### CODE REVIEW

**Comment by etobella** [comment]
Peek 01-03-2021 13-24

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by etobella** [comment]
In 13.0 it was already fixed on https://github.com/OCA/reporting-engine/blob/13.0/report_py3o/models/ir_actions_report.py#L120

**Comment by LoisRForgeFlow** [comment]
It is a bugfix backport, I think we can merge it:

/ocabot merge patch

**Review by albariera — APPROVED** [review]

**Pull request merged**
