### PR TITLE
[PORT] Port report_xls to 9.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Necessary for https://github.com/OCA/account-financial-reporting/pull/147

### CODE REVIEW

**Comment by Garamotte** [comment]
:+1: It works.

I think you should also cherry-pick https://github.com/OCA/reporting-engine/pull/42 when merged in 8.0.

**Comment by StefanRijnhart** [comment]
Thanks. Could you please
- Upgrade the snippet in https://github.com/acsone/reporting-engine/blob/9.0-port-report_xls-ape/report_xls/ir_report.py to new API
- Review #42 and include here if you agree
- Replace description key from __openerp__.py with README.rst?

**Comment by ghost** [comment]
@adrienpeiffer can you rebase please

**Comment by sbidoul** [comment]
@dufresnedavid rebased. Do we still need this module in v9?

**Comment by sbidoul** [comment]
I think we won't work on this module anymore, so feel free to close this one and take over.

**Comment by ghost** [comment]
@sbidoul you should close the PR.

**Pull request closed without merging**
