### PR TITLE
[16][MIG] sql_export_excel

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard migration @yankinmax @ajaniszewska-dev

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Hi, kindly asking a review from last version migration contributors/reviewers @yankinmax @leemannd @ajaniszewska-dev

**Review by yankinmax — APPROVED** [review]

**Comment by legalsylvain** [comment]
hi @florian-dacosta could you fix conflict ? 

thanks !

**Comment by florian-dacosta** [comment]
Hi @legalsylvain, done !

**Review by leemannd — APPROVED** [review]

**Comment by legalsylvain** [comment]
/ocabot merge patch

thanks for your contribution, and thanks for the reviews.

**Pull request merged**
