### PR TITLE
WIP [11.0][NEW] report_pdf_combination

### PR DESCRIPTION
**Pull request by yelizariev**
report that combines multiple pdf into one

### CODE REVIEW

**Comment by yelizariev** [comment]
This module has unfinished CI tests, which I'm not planning to do in near future. If someone wants this to be merged to OCA, please finish those tests yourself. 

I'm ready to assist on module usage if needed.

**Comment by njeudy** [comment]
@yelizariev can you add me to your branch so i can add tests ?

**Comment by yelizariev** [comment]
@njeudy I am not sure that I can provide access to one branch only. I think you can make new PR to OCA repo.

**Comment by yelizariev** [comment]
https://github.com/OCA/reporting-engine/pull/194#issuecomment-552944701

**Pull request closed without merging**
