### PR TITLE
[FIX] report_py3o: fix exception when report must be saved as attache…

### PR DESCRIPTION
**Pull request by lmignon**
…ment

The mehtod  must be called with a list of ids not with a list of browse records

cc @alexis-via @JonathanNEMRY @rousseldenis

### CODE REVIEW

**Review by JonathanNEMRY — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by alexis-via** [comment]
I proposed another fix for report_py3o as a PR to this branch:
https://github.com/acsone/reporting-engine/pull/3
With this PR, when you do a reset to draft on an invoice that has the PDF in attachement, the PDF will be automatically deleted (it works on qweb and didn't work on py3o so far)

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
We really need someone to merge this !

**Comment by alexis-via** [comment]
@lmignon Do you now have commit rights to merge this (following my email on the OCA ML) ?

**Comment by lmignon** [comment]
@alexis-via No I don't have the rights to merge this one.... It's hard to have a dynamic management of this addon when we have to wait for weeks to have a PR merged.

**Comment by alexis-via** [comment]
@lmignon You mean you still don't have commit rights on OCA/reporting-engine ?

**Comment by lmignon** [comment]
@alexis-via 

> @lmignon You mean you still don't have commit rights on OCA/reporting-engine ?

Yes that's what I mean. I don't have commit rights on OCA

**Comment by alexis-via** [comment]
@elicoidal Thanks for your merge ! Could you add commit rights on this project to Laurent Mignon and Florent Aide as discussed in the OCA mailing-list ?

**Comment by sbidoul** [comment]
@elicoidal @alexis-via actually, reporting-engine is under the tools PSC (like server-tools and others) so that means adding @lmignon and @faide in that group. Not that it would be a problem for me but...

If you don't mind I'll do a small experiment and create a Reporting Engine Maintainers group and see if the OCA sync magic does the job. Actually as I read the code it should and it would be a step toward finer grained repo management.

**Comment by sbidoul** [comment]
@faide I don't find you in the OCA database. Do you remember having sent your signed CLA?

**Comment by faide** [comment]
Yes i'm 100% positive on that and i received à confirmation i forwarded to
Laurent mignon
I can find it tomorrow if necessary

**Comment by sbidoul** [comment]
@faide ok, I found it. Let's see if https://github.com/orgs/OCA/teams/reporting-engine-maintaners gets populated during the night.

**Comment by elicoidal** [comment]
> If you don't mind I'll do a small experiment and create a Reporting Engine Maintainers group and see if the OCA sync magic does the job. Actually as I read the code it should and it would be a step toward finer grained repo management.

:+1:

**Comment by alexis-via** [comment]
@sbidoul It seems it didn't get updated during the night...

**Comment by sbidoul** [comment]
@gurneyalex can you check why https://github.com/orgs/OCA/teams/reporting-engine-maintaners is not synchronized from https://odoo-community.org/web#id=112&view_type=form&model=project.project&menu_id=370&action=469

I think the `copy-maintainers` script is a cron under your user on odoo-community.org, right?

**Comment by gurneyalex** [comment]
Hello,

It's a configuration issue: there was a typo in the team name in github ("Reporting Engine Maintaners") -> the matching was failing in the script.

I'm fixing this.

**Comment by gurneyalex** [comment]
@faide you should have received an invitation to join the github team. Can you confirm?

**Comment by faide** [comment]
I have received an invitation yes

On Tue, Mar 21, 2017 at 9:04 AM, Alexandre Fayolle <notifications@github.com

**Comment by sbidoul** [comment]
Thanks @gurneyalex !

**Comment by alexis-via** [comment]
@gurneyalex Thanks for solving this problem ! It will be a big help for the work on py3o in the OCA.

**Pull request merged**
