### PR TITLE
[15.0][MIG] kpi_dashboard

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test on runbot :+1: 

@etobella

**Comment by AaronHForgeFlow** [comment]
BTW, is there any python dependency or some style library needed to be installed? I cannot make the demo dashboard to show in my local computer (clean instance without any other module installed). No errors in the console of the web browser. I just shows empty:
image. Thanks in advance

**Comment by JasminSForgeFlow** [comment]
> BTW, is there any python dependency or some style library needed to be installed? I cannot make the demo dashboard to show in my local computer (clean instance without any other module installed). No errors in the console of the web browser. I just shows empty: image. Thanks in advance

Hi @AaronHForgeFlow,

No nothing special lib is required to run this module.

Thanks

**Comment by AaronHForgeFlow** [comment]
I just noticed the issue happens in enterprise version only

**Comment by etobella** [comment]
Can you add https://github.com/OCA/reporting-engine/pull/576 ?

**Comment by JasminSForgeFlow** [comment]
> Can you add #576 ?

Added, Thanks

**Comment by etobella** [comment]
It is not working properly on runbot. For example, pressing the dashboard view is not showing anything. However, if you use a menu it works. Colors are not the same from 14 to 15
On 14
image

On 15
image

**Comment by brechtverhaeghe** [comment]
> I just noticed the issue happens in enterprise version only

I also can't get the dashboard working in Enterprise without any error on the server side logs or the client side debugger.

**Comment by etobella** [comment]
Can you review @JasminSForgeFlow

**Comment by miquelrosell99** [comment]
image
I'm getting a blank page when trying to see the KPI value, but showing raw value from history works
Any help?

**Comment by AaronHForgeFlow** [comment]
@OCA/reporting-engine-maintainers  can you remove this from stale?

**Comment by etobella** [comment]
@JasminSForgeFlow Can you review all the comments?

**Review by dreispt — APPROVED** [review]

**Review by etobella — CHANGES_REQUESTED** [review]
It was not working and no changes where applied after that

**Comment by dreispt** [comment]
Superseded by #814

**Pull request closed without merging**
