### PR TITLE
[IMP] bi_sql_editor : conserve cron settings, when setting materialized view to draft ; Set correct default values for cron and enable it

### PR DESCRIPTION
**Pull request by legalsylvain**
port residual changes introduced in #559

CC : @etobella, @tfossoul 

+ add me as maintainers.

### CODE REVIEW

**Review by tfossoul — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by tfossoul** [comment]
Hi @legalsylvain pay attention to this https://github.com/OCA/reporting-engine/pull/559/commits/796b27aebbf68e45b47afdce1efc53fd4876a729

This break our unit tests on our projects last day of each month..

**Comment by legalsylvain** [comment]
Hi @tfossoul 
Thanks for that point.
Could you make a PR ?
Regards.

**Review by andreampiovesana — APPROVED** [review]
merge

**Pull request merged**
