### PR TITLE
9.0 Another report_py3o README update

### PR DESCRIPTION
**Pull request by alexis-via**
I forgot one of the most important thing in the installation procedure : the command to start libreoffice !

### CODE REVIEW

**Comment by alexis-via** [comment]
Sorry, it was against the wrong branch.

**Comment by pedrobaeza** [comment]
Don't open a new PR!!

**Comment by pedrobaeza** [comment]
Well, I have changed base branch to merge into, but it still doesn't work, so it seems that at the end we need a new PR.

**Comment by alexis-via** [comment]
To make things clear: I wanted to propose the PR to Florent's branch, but I made a mistake and proposed it against OCA's branch. I made a new "good" PR just after closing this one and my new PR has already been merged by Florent.

**Pull request closed without merging**
