### PR TITLE
[FIX] report_csv: Assign 'reportname' variable before accessing it

### PR DESCRIPTION
**Pull request by rousseldenis**
@AnizR @adrienpeiffer

### CODE REVIEW

**Comment by rousseldenis** [comment]
@adrienpeiffer In addition of this fix, shouldn't an error re-raise werkzeug InternalServerError instead ?

Like this : https://github.com/odoo/odoo/blob/16.0/addons/stock/controllers/main.py#L38

**Review by ioans73 — APPROVED** [review]

**Review by AnizR — APPROVED** [review]
Great!

**Comment by adrienpeiffer** [comment]
@rousseldenis Totally agree with you !

**Comment by rousseldenis** [comment]
@adrienpeiffer @AnizR @ioans73 In addition, I've added the InternalServerError return and a test for controller to increase coverage

**Review by AnizR — APPROVED** [review]

**Pull request merged**
