### PR TITLE
[IMP] kpi_dashboard: Set history & Add compute on the fly & Show value on kpi form

### PR DESCRIPTION
**Pull request by etobella**
following the comments of #415  I made this PR. Also, the value of the kpi can be shown directly on the KPI form and history using the show value button

@pedrobaeza @legalsylvain

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
I miss a date/datetime reference in the historization, and the possibility to define the scope of the KPI (hourly, daily, weekly, etc), for not storing always a new entry if still in the same range (or store the last one only). This is critical as your cron will be executed daily, but a weekly KPI will have 7 historization records!

**Comment by etobella** [comment]
Good point!!! I did not think about it, but it has a lot of sense :wink: WOI

**Comment by etobella** [comment]
Comments attended, now we can define a interval scope :smile:

**Comment by legalsylvain** [comment]
Hi @etobella. tested. works like a charm thanks ! 
I made a little PR to improve the new feature. https://github.com/tegin/reporting-engine/pull/1

**Comment by etobella** [comment]
Good for me!

**Review by jarroyomorales — APPROVED** [review]
Functional test LGTM! :+1:

**Review by legalsylvain — APPROVED** [review]

**Comment by etobella** [comment]
@legalsylvain I have some improvements that can be really interesting, like allowing to refresh the compute_on_fly using an interval, Do you prefer this here or on a different PR?

**Comment by etobella** [comment]
https://github.com/tegin/reporting-engine/tree/12.0-imp-kpi-onfly

**Comment by legalsylvain** [comment]
Hi @etobella, 

First thanks for there improvements.

I think it can be integrated in this PR, as it is improving the new compute on the fly feature.

Good idea to add the context (https://github.com/tegin/reporting-engine/commit/aff958e21b4534ca36edf1e4b5d05b1a1e1ddbe2) do you think it could be possible to add also a domain ? 
This is a current regression, regarding the ``web_dashboard_tile`` features. (https://github.com/OCA/web/blob/10.0/web_dashboard_tile/models/tile_tile.py#L165)

kind regards.

**Comment by etobella** [comment]
I will check the domain, I am not sure if we can do something specific :wink: but I will try

**Pull request merged**
