### PR TITLE
8.0 port of report_xls module

### PR DESCRIPTION
**Pull request by luc-demeyer**
I want to create a PR for the OCA 8.0 branch of the reporting engines but this branch doesn't exist yet.
Hence I have selected a PR into master.
Can you someone also create the 8.0 branch and put my 8.0 version of the report_xls module into that branch (or alternatively explain me how to do it myself) ? 

Tx,
Luc

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Luc, we haven't created yet because first we used to set Travis tests and then fix all PEP8 and pylint issues. Please work in this area (as I see you have done, except for Travis), and then we will create 8.0 branch from 7.0.

**Comment by dreispt** [comment]
Pedro, the v8 branch should start with no active modules, only "unported" ones.Why can't it be created right away, like all other projects did?=

**Comment by pedrobaeza** [comment]
Because, "unported" modules don't have PEP8 fixed, and you will start migration from them.

**Comment by luc-demeyer** [comment]
Pedro,

Create the reporting-engine branch from V7 is not a good idea since there are currently only 2 modules in that project and at least for my module (report_xls) I had to make some changes for V8.

I am not sure about the ‘base_report_assembler’ but I think that it’s better to first test/port this module to V8 before putting it in the 8.0 branch.

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by pedrobaeza** [comment]
No, I'm only saying to put in the 8.0 branch in the `__unported__` dir the modules deactivated, but with PEP8, but as you are saying, there's only two modules in there, and you are migrating already one. Let me then prepare the branch and I'll tell you.

Regards.

**Comment by luc-demeyer** [comment]
Pedro,

The V8.0 version of the report_xls module is PEP8 compliant and has been tested on V8. 

I am also preparing PR’s for other ported V8 modules that depend on report_xls hence why block this ? 

I think that it’s better to start with a ‘clean’ reporting-engine V8 branch and accept the report_xls PR and wait upon C2C to port the ‘base_report_assembler’ module to V8 and make a PR once they are ready.

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by pedrobaeza** [comment]
I have already created 8.0 branch. Please create the PR against that branch (you'll need to rebase).

**Comment by dreispt** [comment]
@pedrobaeza sorry for nagging, but you could as well make it the default branch.

**Comment by pedrobaeza** [comment]
I would like to, but this is a task only reserved for OCA board members. I can create new branches, but not change the default one. @gurneyalex, can you help us?

**Comment by gurneyalex** [comment]
made 8.0 the default branch. I can remove the master branch if required (just ask, I'm not sure if special priviledges are needed)

**Comment by pedrobaeza** [comment]
Thank you, Alexandre. I have just deleted it (I'm able to do that operation), so this PR has been automatically closed.

**Comment by luc-demeyer** [comment]
Thanks Pedro, 

I have now created the PR against the 8.0 branch.

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Pull request closed without merging**
