### PR TITLE
Update dotfiles, test with GitHub actions

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
By adding `deb` external dependencies in the manifest, tests pass and everything gets installed on ruboat.

**Comment by pedrobaeza** [comment]
Is such key something customized for runboat?

**Comment by sbidoul** [comment]
> Is such key something customized for runboat?

And running the tests. It's part of the [oca-ci image installation script](https://github.com/OCA/oca-ci/blob/9eff1d7235a52bde738b6ed1503e766a38f6dd70/bin/oca_install_addons#L40).

**Comment by pedrobaeza** [comment]
OK, maybe we should have a how to page about CI. Merging this.

**Pull request merged**
