### PR TITLE
[ADD] [16.0] report_display_name_in_footer

### PR DESCRIPTION
**Pull request by Shide**
Adds document name in report PDF footers.

Can configured via parameteres (see CONFIGURE.md)

MT-5999 @moduon @yajo @rafaelbn @EmilioPascual @fcvalgar @Gelojr please review if you want :)

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review, 

LGTM Thank you @Shide 

image

image


image

**Review by Gelojr — APPROVED** [review]
Very good job @Shide LGTM
https://www.loom.com/share/410348902d3d45d88ca1dce5065fadf9?sid=d326d401-b936-4d9a-8cc4-624c2129a465

**Review by rafaelbn — APPROVED** [review]
👍🏼 Functional review

**Comment by rafaelbn** [comment]
Hello @HviorForgeFlow @lmignon @alexis-via  ,

Please, could you review this PR 🙏🏼 ! is easy, intelligent and simple! 😄 

Thank you! ❤️

**Review by EmilioPascual — APPROVED** [review]
Wonderful module! Very good solution to the problem.
It would be nice to have an option per report, in stock.picking you have several reports. Maybe in a future module.

**Review by lmignon — APPROVED** [review]
Nice one. LGTM (code review)

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
