### PR TITLE
[15.0][MIG] sql_export_mail: Migration to 15.0

### PR DESCRIPTION
**Pull request by BT-ssteiner**

### CODE REVIEW

**Review by BT-anieto — APPROVED** [review]
LGTM

**Review by BT-ojossen — APPROVED** [review]
LGTM

**Comment by legalsylvain** [comment]
@florian-dacosta could you review ?

**Review by florian-dacosta — APPROVED** [review]
LGTM code review (no test)
It would be nice to forward port the tests to v16 so it is not lost during migration to v17 or v18
Would you mind doing a PR for this @BT-ssteiner ?

**Comment by BT-ssteiner** [comment]
Hello @florian-dacosta 
Thank you for your review. The PR for the unit tests is created #862

**Comment by BT-ssteiner** [comment]
Hello @legalsylvain 
Can we merge this too?

**Pull request merged**
