### PR TITLE
[17.0][MIG] report_async: Migration to 17.0

### PR DESCRIPTION
**Pull request by sakthi-shan**
cc: @SodexisTeam

### CODE REVIEW

**Review by amkarthik — APPROVED** [review]
Code review 👍🏾

**Comment by mpascuall** [comment]
Hi! Could you fix the pr name? the correct one would be [MIG] report_async: Migration to 17.0

**Comment by ppyczko** [comment]
Hi @sakthi-shan, code looks good. Can you please rebase to rerun the runboat? As it is pending and we can't test the functionality without it, thank you in advance!

**Comment by mpascuall** [comment]
My bad, correct pr name would be [17.0][MIG] report_async: Migration to 17.0 
Sorry!

**Review by ppyczko — APPROVED** [review]
LGTM, tested locally and works great!

**Review by mpascuall — APPROVED** [review]
LGTM, code review and tested in local odoo and it works

**Comment by sakthi-shan** [comment]
@kittiu

**Comment by kittiu** [comment]
> @kittiu

Sorry I do not have merge right.

**Comment by sakthi-shan** [comment]
@OCA/reporting-engine-maintainers

**Pull request merged**
