### PR TITLE
[16.0] [IMP] report_py3o: use the standard file name behavior when zipping report files

### PR DESCRIPTION
**Pull request by glitchov**
File names should be the same whether we download a single report or if we zip several report files.

Forward port of #829

### CODE REVIEW

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by benwillig — APPROVED** [review]
Code review and functional tests ok

**Comment by ThomasBinsfeld** [comment]
ping @OCA/reporting-engine-maintainers 

This one is reopening of #830. It's tested and production-ready.

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by ThomasBinsfeld** [comment]
Thanks!

**Pull request merged**
