### PR TITLE
[14.0][MIG] bi_view_editor

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by tonygalmiche** [comment]
why this error ?

image

**Comment by astirpe** [comment]
@tonygalmiche you are right, it was a bug! Should be fixed now.

**Comment by tonygalmiche** [comment]
While doing some testing I deleted a table alias and then got this message:
```
  File "/home/odoo/build/OCA/reporting-engine/setup/bi_view_editor/odoo/addons/bi_view_editor/models/bve_view.py", line 125, in _compute_er_diagram_image
    line.model_id.name + " " + line.table_alias,
Exception
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: must be str, not bool
```
And now i can't correct my mistake anymore. I have to delete everything and start over

**Comment by astirpe** [comment]
@tonygalmiche thanks for letting me know!
Now the table alias is a mandatory field and deleting its value is not possible anymore.

**Comment by tonygalmiche** [comment]
Thank you for the corrections

The order of the fields in the 'Details' tab is not taken into account in the tree view

I think we should prohibit the addition of relation in the 'Details' tab because by wanting to do it this resulted in a new error

**Comment by astirpe** [comment]
@tonygalmiche fixed!

**Review by tonygalmiche — APPROVED** [review]
@astirpe thank you  for the corrections.

LGTM : Functional review only with runbot : 
image

**Review by StefanRijnhart — APPROVED** [review]
code review

**Comment by StefanRijnhart** [comment]
@astirpe I'm afraid the merge failed on pyupgrade insisting on replacing % substitution with str.format
```
 --- a/bi_view_editor/models/bve_view.py
+++ b/bi_view_editor/models/bve_view.py
@@ -382,8 +382,8 @@ class BveView(models.Model):
                         line.field_id.name,
                         line.join_node,
                     )
-            bve_view.query = """SELECT %s\n\nFROM %s
-                """ % (
+            bve_view.query = """SELECT {}\n\nFROM {}
+                """.format(
                 AsIs(select_str),
                 AsIs(from_str),
             )
```
(even though that was configured out in https://github.com/OCA/oca-addons-repo-template/pull/49)

Anyway, can you amend your commit with this change?

**Comment by StefanRijnhart** [comment]
Trying again after @yajo's helpful https://github.com/OCA/reporting-engine/pull/503.

/ocabot merge nobump

**Pull request merged**
