### PR TITLE
[NEW][8.0] report_header_full_width: More header width for company address.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc. @rafaelbn

### CODE REVIEW

**Comment by rafaelbn** [comment]
:+1:  thanks.

**Comment by pedrobaeza** [comment]
Why don't you propose a patch to Odoo? This is clearly a non-desired feature (if you don't want to talk about a bug).

**Comment by sergio-teruel** [comment]
Ok.. I think the same as you... so i close this PR and propose to odoo directly.

**Comment by sergio-teruel** [comment]
PR proposed to odoo @rafaelbn @pedrobaeza 
https://github.com/odoo/odoo/pull/11031

**Pull request closed without merging**
