### PR TITLE
[13.0][IMP] base_comment_template: Add function to get_comment_template records

### PR DESCRIPTION
**Pull request by victoralmau**
Add function to get_comment_template records.

It's related to https://github.com/OCA/account-invoice-reporting/pull/174#discussion_r609506163

Please @CarlosRoca13 and @ernestotejeda can you review it?

@Tecnativa TT26758

### CODE REVIEW

**Review by ernestotejeda — APPROVED** [review]

**Review by ernestotejeda — COMMENTED** [review]
I think the 'priority' field should be taken into account here, isn't it?

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by victoralmau** [comment]
> I think the 'priority' field should be taken into account here, isn't it?

Actually, in `get_comment_template_records()` priority appear:

```
....
templates = self.env["base.comment.template"].search(
            default_dom, order="priority"
        )
.....
```

**Comment by ernestotejeda** [comment]
> Actually, in get_comment_template_records() priority appear

oh yes it's there, sorry :)

**Comment by victoralmau** [comment]
I have try to apply in 14.0 (FWP) but it's not apply migration correctly, right?  (`base.comment.template` model have disappear)
What do you think @pedrobaeza  and @CarlosRoca13 ?

**Comment by pedrobaeza** [comment]
We need to check what was done in v14 and maybe compatibilize it with this scheme. We have been a bit late to the party and a version jump has been made.

**Pull request merged**
