### PR TITLE
[13.0][MIG] report_csv

### PR DESCRIPTION
**Pull request by kongrattapong**
Standard migration.

### CODE REVIEW

**Comment by kittiu** [comment]
From the runbot,

2020-01-31 05:14:31,227 158 WARNING openerp_test odoo.models: The model report.report_csv.partner_csv has no _description

**Comment by kittiu** [comment]
Functional tested OK

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
@kongrattapong please rebase

**Comment by kongrattapong** [comment]
@lmignon  Can you merge this pr?, Thank you

**Comment by lmignon** [comment]
@kongrattapong we only have one approval :-(

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Comment by LoisRForgeFlow** [comment]
Ready to merge! :wink:

**Pull request merged**
