### PR TITLE
[15.0][FIX] bi_sql_editor: Set tomorrow date correctly.

### PR DESCRIPTION
**Pull request by victoralmau**
Set tomorrow date correctly.

It will also be necessary to fix it in 14.0

Please @pedrobaeza can you review it?

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
Don't see what it is fixing. What is the error ?
However, syntax is lighter.  👍

**Comment by victoralmau** [comment]
> Don't see what it is fixing. What is the error ? However, syntax is lighter. +1

The date was impossible: https://github.com/OCA/reporting-engine/actions/runs/3583173092/jobs/6028290242#step:8:238

**Comment by pedrobaeza** [comment]
The problem happens when running around midnight, joined with the timezone nos being adjusted, leads to the test not working. This time, is better to always add a full day (24 hours) for avoiding the problem.

/ocabot merge patch

**Comment by pedrobaeza** [comment]
>The date was impossible

Ah, also that one, last day of each month, the tests fail.

**Comment by legalsylvain** [comment]
Thanks for the explanation.

**Pull request merged**
