### PR TITLE
[15.0][MIG]  report_xlsx

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
standard migration of the module report_xlsx to version 15.0

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@ChrisOForgeFlow can you help with the js?

**Comment by aisopuro** [comment]
If it helps, I made an ugly solution in my migration of `report_xml` due to the report handler service being strictly private in version 15: https://github.com/OCA/reporting-engine/pull/550/files#diff-364e5c801ea1b16dac1cd54935f7851db3173417864b4bebb485b94c0bb6599eR6.

Hopefully that can help you with the JS. If you come up with a better solution than mine that could also be applied in `report_xml`, please ping me on that PR: I would love to be able to have a better solution :sweat_smile: .

**Comment by JoanMForgeFlow** [comment]
@ChrisOForgeFlow Thanks so much for your help! Its working :)

**Review by AaronHForgeFlow — APPROVED** [review]
It just works

**Comment by JoanMForgeFlow** [comment]
@lmignon, @alexis-via  or @faide could you please merge this module? Thanks

**Review by mariadforgeflow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Cache issue again in pre-commit.

@sbidoul Do you have a way to easily invalidate the cache of pre-commit jobs?

If not, we just need to wait a couple of days to try again the merge.

**Comment by pedrobaeza** [comment]
Trusting on reviews:

/ocabot migration report_xlsx

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
It seems the problem with cached pre-commit is still there. Merging manually for now as no version bump is required.

**Comment by BT-ojossen** [comment]
Hello @JoanMForgeFlow, could it be that with this module installed, the default creation of a pdf is not working anymore?
Thanks for having a look.

**Comment by AaronHForgeFlow** [comment]
@BT-ojossen if you uninstall this module is the default creation of pdf working? are you using enterprise version or community?

**Comment by BT-ojossen** [comment]
@JoanMForgeFlow
Yes, when I uninstall the module, the pdf creation is working. I'm using enterprise.

**Comment by AaronHForgeFlow** [comment]
That seems something to investigate, I originally tested this in community version only.

**Comment by BT-ojossen** [comment]
Hi @AaronHForgeFlow 
Thanks for your answer. Would it be possible that you have a look at this issue as you know best what you already did.
Thanks a lot.

**Pull request merged**
