### PR TITLE
[MIG] kpi_dashboard: Migration to 14.0

### PR DESCRIPTION
**Pull request by etobella**
Just some minor changes, but nothing relevant from 13.0 (#446)

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Dashboards looks like they overlap, but I am not sure if I configured them correctly:
image

Nice work as always. Thanks a lot!

**Comment by etobella** [comment]
I found a small issue from pre-commit, @AaronHForgeFlow  I am unable to reproduce the error you found :thinking:

**Comment by AaronHForgeFlow** [comment]
Actually, I could not reproduce that issue on runbot, only in my local, so it must by my fault in this case.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests.

**Review by alan196 — APPROVED** [review]
Functional Review 👍

**Review by StefanRijnhart — APPROVED** [review]

**Comment by fmdl** [comment]
@etobella can you add more details to build graph ?

**Pull request merged**
