### PR TITLE
[16.0][FIX] report.py: docids = none

### LINKED ISSUE #790: [16.0] [BUG] report_routes with no docids
## Module
report_xml

## Describe the bug

Line in report_routes:

https://github.com/OCA/reporting-engine/blob/f5c04ca190fa842497b7351f7f965725d9881ec6/report_xml/controllers/report.py#L31C5-L31C5

`docids = [int(_id) for _id in (docids or "").split(",")]`

with no docids is:
`for _id in ("").split(",")` 
and 
`int('')`
is not possibile

so with `docids = none` generates:

**ERROR TRACE**

  File "/home/odoo-user/odoo/16/application-env/oca-addons/reporting-engine/report_xml/controllers/report.py", line 31, in report_routes
    docids = [int(_id) for _id in (docids or "").split(",")]
  File "/home/odoo-user/odoo/16/application-env/oca-addons/reporting-engine/report_xml/controllers/report.py", line 31, in <listcomp>
    docids = [int(_id) for _id in (docids or "").split(",")]
ValueError: invalid literal for int() with base 10: ''

**Expected behavior**
similar to 14.0 version, is possible resolves changing in:

```
if docids:
    docids = [int(_id) for _id in (docids).split(",")]
```

### PR DESCRIPTION
**Pull request by TennyMkt**
resolves https://github.com/OCA/reporting-engine/issues/790

### CODE REVIEW

**Review by danall59 — APPROVED** [review]
The code has been verified and tested.
Merging is recommended.
It's OK!

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by SirAionTech — APPROVED** [review]
Thanks for the PR!
A test case covering this fix would be great, but since this is just one line it looks already good to me as is.

Note that the core does something similar in
https://github.com/odoo/odoo/blob/114e31521beb1d00f85f8a19959006dfe62708a0/addons/web/controllers/report.py#L31-L32

**Pull request merged**
