### PR TITLE
[FIX] prevent ocabot merges

### PR DESCRIPTION
**Pull request by bodedra**
Comment Ref: https://github.com/OCA/reporting-engine/pull/334#issuecomment-611683753

Error log:

Firefox_Screenshot_2020-04-09T17-07-24 995Z

### CODE REVIEW

**Comment by bodedra** [comment]
@dreispt @pedrobaeza @etobella @guewen @max3903 @lmignon

**Review by lmignon — APPROVED** [review]

**Comment by pedrobaeza** [comment]
But shouldn't this be solved at server-env level? I have the same error in other branch (11.0) in other repo (l10n-spain): https://travis-ci.org/github/OCA/l10n-spain/jobs/670689281#L2437

And having to put this on each one it's a stopper, and more only being affected because subsequent dependencies, not by direct use.

@simahawk I think you were involved in some patch about this. What is the status?

**Comment by simahawk** [comment]
I've just finished fixing tests here https://github.com/OCA/server-env/pull/45 :wink:

**Comment by pedrobaeza** [comment]
Thanks, is the same applicable to 11.0 as well?

**Comment by bodedra** [comment]
Thank you Team for your quick response. I will rebase my PR and see output.

Close with reference: https://github.com/OCA/server-env/pull/45

**Comment by simahawk** [comment]
> Thanks, is the same applicable to 11.0 as well?

yes, but needs some adaptation. Some files' structure has changed.

**Comment by pedrobaeza** [comment]
Are you doing that adaptation?

**Comment by simahawk** [comment]
I have no time now, I'll check later or at worse next week.

**Comment by pedrobaeza** [comment]
OK, if you are not able, ping me and I'll try, although I don't know that modules in deep.

**Comment by simahawk** [comment]
v11 https://github.com/OCA/server-env/pull/46

**Pull request closed without merging**
