### PR TITLE
[11.0][ENH] sql view - allow group operator

### PR DESCRIPTION
**Pull request by richard-willdooit**
Replaces #344

Adds the possibility, for float and integer columns, to
apply a group operator (average, min, max).

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM! Functional review.

**Comment by richard-willdooit** [comment]
@CasVissers Do you know what we need to do to get this merged?

**Comment by CasVissers-360ERP** [comment]
@legalsylvain Think this one is also ready to merge?

**Review by legalsylvain — APPROVED** [review]
/ocabot merge

**Comment by richard-willdooit** [comment]
@legalsylvain :( I don't understand the error - my expertise is not that great.  It appears to be a test unrelated to my changes !?

**Comment by legalsylvain** [comment]
Hi @richard-willdooit : I have no idea.
could you try to rebase your PR ?

**Comment by dreispt** [comment]
The `report_qr` tests are failing.
I created issue https://github.com/OCA/reporting-engine/issues/383 for this.

**Pull request merged**
