### PR TITLE
[16.0][MIG] report_py3o

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Branch is green !

**Review by BT-anieto — APPROVED** [review]
Functional check OK

As a suggestion, I would specify better in the readme the path 
[report_py3o]
  root_tmpl_path=/odoo/templates/py3o
since it is a bit unclear for me how to configure it

**Comment by alexis-via** [comment]
Dear maintainers,
This PR blocks all other PRs of modules that depend on report_py3o... so it would be cool to merge it.
I use this code in production since 01/01/2023 and it works like a charm.

**Pull request merged**
