### PR TITLE
[14.0][ADD]Report Label Documentation precisions

### LINKED ISSUE #705: [14.0]Report Label produce empty PDF with default label format agipa
Hi,

I'm trying to use the report label module.
Here is the default setup I used.

image

Sadly, this configuration produce an empty PDF, is there any restriction regarding python module version or wkhtml ?

### PR DESCRIPTION
**Pull request by flotho**
FIX #705

### CODE REVIEW

**Comment by flotho** [comment]
@legalsylvain , review are welcome

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
Could you take a look on CI precommit error ?

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
(maybe squach the 2 commits)

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Thanks!

**Pull request merged**
