### PR TITLE
[FIX] add slash in url in qwebactionmanager.js

### PR DESCRIPTION
**Pull request by ruben-tonetto**
For me, it does work with added slash
if not i receive an error indicating that the url ...:8069report/... is not found

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is working as expected in other addons. Can you specify how you reproduce the error?

**Comment by ruben-tonetto** [comment]
Sorry, you are right!
The problem was in another module
I should have tested before with empty database.

**Comment by ruben-tonetto** [comment]
ps: i've tried the module report_xlsx in runbot and it gives an error when trying to export two records; this is the reason that made me sure of the problem

**Comment by pedrobaeza** [comment]
The module is not usable without another module that makes use of their possibilities, so I'm curious how do you reproduce the problem.

**Pull request closed without merging**
