### PR TITLE
[15.0][MIG] report_csv: Migration to 15.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Migration report_csv to 15.0

PR for migration in version 14.0 : #511

### CODE REVIEW

**Review by kanda999 — APPROVED** [review]
Functional review: Working as expected.

**Comment by etobella** [comment]
Can you rebase in order to check runboat?

**Comment by MiquelRForgeFlow** [comment]
@adrienpeiffer please rebase :)

**Comment by JuanyDForgeflow** [comment]
@adrienpeiffer please rebase

**Review by gaikaz — APPROVED** [review]
Code review. LGTM.

**Pull request merged**
