### PR TITLE
 [14.0][MIG] report_xlsx: Migration to 14.0

### PR DESCRIPTION
**Pull request by tupaq**

### CODE REVIEW

**Review by tonygalmiche — CHANGES_REQUESTED** [review]
same problem : 

image

**Comment by tupaq** [comment]
You may need to update the repository.
In case the problem persists.
Could send the message that appears in the odoo logs.

**Comment by tonygalmiche** [comment]
> You may need to update the repository.
> In case the problem persists.
> Could send the message that appears in the odoo logs.

I am doing the test with runbot, I do not see the server logs

**Comment by tupaq** [comment]
> > You may need to update the repository.
> > In case the problem persists.
> > Could send the message that appears in the odoo logs.
> 
> I am doing the test with runbot, I do not see the server logs

Is fixed:
The error is because the field is not defined:
report_file in report_xlsx/demo/report.xml

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by feketemihai — APPROVED** [review]

**Review by florian-dacosta — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Could rebase and run latest pre-commit config? that should fix the error during the merge https://travis-ci.com/github/OCA/reporting-engine/jobs/423958890

**Comment by ventor-dev** [comment]
@tupaq , could you, please, rebase as requested by @LoisRForgeFlow so that can be merged?

**Comment by tupaq** [comment]
> Could rebase and run latest pre-commit config? that should fix the error during the merge https://travis-ci.com/github/OCA/reporting-engine/jobs/423958890

@LoisRForgeFlow is rebased.

**Comment by ventor-dev** [comment]
@LoisRForgeFlow , could you, please, merge?

**Comment by ventor-dev** [comment]
@LoisRForgeFlow , anybody can merge this change?

**Review by mamcode — APPROVED** [review]
Functional Review :+1:

**Pull request merged**
