### PR TITLE
[17.0] [MIG] report_xml: Migration to 17.0

### PR DESCRIPTION
**Pull request by anikeenko-viktor**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check missing pre-commit changes in the last commit.

/ocabot migration report_xml

**Review by gurneyalex — APPROVED** [review]

**Review by john-herholz-dt — APPROVED** [review]
Looks good.

**Review by john-herholz-dt — APPROVED** [review]

**Comment by aisopuro** [comment]
I rebased this migration on top of `17.0` and resolved the conflict in `requirements.txt` (it had been updated in a previously merged PR it seems).

All checks are passing now, can @gurneyalex or @john-herholz-dt recheck and merge? The only change should be that `requirements.txt` now includes the requirments of previously merged modules.

**Review by john-herholz-dt — APPROVED** [review]
Changes look good. I did also a functional test on runboat.
Got the demo report as expected.

Approved!

**Comment by aisopuro** [comment]
@gurneyalex @john-herholz-dt is there something more that I need to do, or anything I can do to help get this merged? I don't mean to spam messages, I'm just worried this slipped through the cracks somewhere.

**Comment by john-herholz-dt** [comment]
@gurneyalex regarding last message. Can you confirm my knowledge of the merge process:
When PR is labeled ready to merge, a maintainer gets notified and needs to run the OCABOT merge command, right?

When the maintainer does not respond, the only option is to ping the person?

**Comment by gurneyalex** [comment]
@aisopuro no pb. It sometimes takes a little bit of time until someone can get back to the PR and merge it. 

@john-herholz-dt that's it yes.

**Pull request merged**
