### PR TITLE
[12.0][MIG] report_qweb_element_page_visibility

### PR DESCRIPTION
**Pull request by Saran440**
- [x] [BUG] : not support when print document more than 1

### CODE REVIEW

**Comment by cvinh** [comment]
:+1: We use it in production

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM (functional)

**Comment by ioans73** [comment]
We have detected a problem related to this issue https://github.com/OCA/reporting-engine/issues/349. Can you give it a look?

**Comment by Saran440** [comment]
@ioans73 yes, I found bug. But I don't know how to solve it.
In javascript it sum all page document.
`var toPage = document.getElementsByClassName('topage');`
Do you have any ideas to suggest?

**Comment by ioans73** [comment]
Hi, @Saran440 I've been testing and found the solution.
I tried to PR your fork but I couldn't. [Here is the commit](https://github.com/Studio73/reporting-engine/commit/d1854dd3fdcb370d578329ad7ae99fa7fc01e6a9) can you check if also works for you?

**Comment by Saran440** [comment]
@ioans73 Not work. I test function `last-page`
print 1 document and many page but it show every page.

**Comment by ioans73** [comment]
Hi, we have tested several cases including printing a document with a few pages, using the class `last-page` in the footer and the footer only apeared in the last page, so it worked correctly for me. Can you give me more info on how have you tested it? In which tag/element have you used the class?

**Comment by Saran440** [comment]
My code is :
```
<div class="article">
   <-------body------->
</div>
<div class="footer">
      <div class="row pt80">
                <------------last-page left footer----------->
                <div class="col-8 last-page text-center">
                    (<span t-esc="o.amount_text(o.amount_total)"/>)
                </div>
                <------------last-page right footer----------->
                <div class="col-4 last-page text-right">
                    <span t-field="o.amount_total"/>
                </div>
     </div>
</div>
```

**Result** 1 document but it's show every page:
Selection_002

**Comment by kongrattapong** [comment]
@Saran440 I'm test @ioans73 commit and it's working.

**Comment by ioans73** [comment]
I test your structure and works correctly:

**Result:**

qweb_page_visibility_1

qweb_page_visibility_2

**Comment by Saran440** [comment]
@ioans73  @kongrattapong 
I'm sorry, my typo that `vars.sitepage === vars.sitepage` but I fixed, it's work.
Thank you for your help

**Review by ioans73 — APPROVED** [review]

**Comment by ioans73** [comment]
Hi, @Saran440 

I notice you copy/paste the patch I made, whould be better if you cherry-pick my commit isn't it?
And also your error would have been avoided.

**Comment by Saran440** [comment]
@ioans73 yes, it's good idea and I fixed it. Thank you. :+1:

**Pull request merged**
