### PR TITLE
[10.0][MIG] report_qweb_signer

### PR DESCRIPTION
**Pull request by pedrobaeza**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Failing because of report_qweb_watermark module.

**Review by chienandalu — APPROVED** [review]
Tested cases on runbot:

- Set model to Invoice [open|paid].
- Print open invoice: signed
- Print draft invoice: unsigned.
- Print paid invoice: signed.

**Comment by pedrobaeza** [comment]
@luismontalba please review

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Pull request merged**
