### PR TITLE
[IMP] update dotfiles

### PR DESCRIPTION
**Pull request by yajo**
Make @StefanRijnhart happy fixing https://github.com/OCA/oca-addons-repo-template/pull/49#issuecomment-823383778.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! I noticed a previous update was scripted for all repos.Can't you just run that script a couple of times a year?

**Comment by yajo** [comment]
@sbidoul has the script-fu, I don't know how that works TBH. 🤷🏼‍♂️

**Comment by StefanRijnhart** [comment]
Ah OK. But again thanks for solving this particular case.

**Comment by sbidoul** [comment]
Well, I'm just running `copier -f update`. Nothing automated yet.

**Comment by sbidoul** [comment]
Or rather, wip script here: https://github.com/OCA/maintainer-tools/pull/486

**Comment by yajo** [comment]
Oh yes, I ran that too. I was talking about something that updated all branches of all repos at once.

**Pull request merged**
