### PR TITLE
8.0 port of report_xls module

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You have to rebase your PR against 8.0 branch for being correctly handled by Github.

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by luc-demeyer** [comment]
Pedro,

I am still very unfamiliar with git and the way git is used within the OCA.

I tried the rebase on my local copy and after that performed the ‘git push –f’ command but got ‘Everything up-to-date’ in return. 

Hence I need some help since I don’t know how to move forward on this PR.

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by pedrobaeza** [comment]
Hi, Luc, this is what you have to do:
- `git clone https://github.com/luc-demeyer/reporting-engine.git -b 8.0` for downloading your forked repository in the corresponding branch (please do it again in a clean directory although you already have it in another place).
- Go to the created `reporting-engine` folder.
- `git remote add parent https://github.com/OCA/reporting-engine.git` for adding the reference for the "parent" repository.
- `git fetch parent` for retrieving data from parent repository.
- `git rebase parent/8.0` for including differences of the parent branch in your branch.
- Resolve conflicts generated by the rebase (there are several of them), using `git mv` for moving files and editing manually some files.
- Then do `git add .` for notifying git that you have fixed these files, and type `git rebase --continue` for finishing the rebase.
- At last, make `git push -f`to move changes to Github remote repository.

**Comment by luc-demeyer** [comment]
Thanks Pedro,

I performed the actions suggested by you and now the Travis CI build passed successfully.

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by pedrobaeza** [comment]
Thanks.

:+1:

**Comment by anthony-muschang** [comment]
I test it, it's ok for me.
 :+1:

**Comment by pedrobaeza** [comment]
OK, with 2 approvals and more than 5 days from the proposal, I proceed with the merge.

**Comment by luc-demeyer** [comment]
Tx

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Pull request merged**
