### PR TITLE
[13.0][FIX] report_xlsx: rename a file

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
😏

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Fast-traking, please?

**Review by etobella — APPROVED** [review]

**Review by jarroyomorales — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@OCA/reporting-engine-maintainers can we get this merged?

**Comment by HviorForgeFlow** [comment]
ping @MiquelRForgeFlow

**Comment by MiquelRForgeFlow** [comment]
@dreispt My initial goal for this PR is lot. Could you merge it anyways? If not, then I'll close it.

**Pull request merged**
