### PR TITLE
[14.0][IMP] report_xlsx: add option for PDF creation

### PR DESCRIPTION
**Pull request by TheMule71**
Use libreoffice to create PDF reports.

### CODE REVIEW

**Review by andreampiovesana — APPROVED** [review]
good

**Comment by etobella** [comment]
I might prefer to have this on separate module. It seems interesting, but it breaks the idea of the original module.

**Review by alepit — APPROVED** [review]

**Review by MarcoCalcagni — APPROVED** [review]
LGTM

**Review by etobella — CHANGES_REQUESTED** [review]
This PR is adding some extra dependencies on a module and it is not necessary. You need to add a new module that adds this behavior

**Comment by andreampiovesana** [comment]
> This PR is adding some extra dependencies on a module and it is not necessary. You need to add a new module that adds this behavior

not really, this feature is requested if you use xlsxwriter for all your reports.
It is much much faster than qweb+wkhtmtopdf (not maintained) , specially for report > 100 pages
and you can debug. Libreoffice headless is used also in report_py3o for conversion (where I copied the functionality)
If you not enable xlsx_to_pdf the flow is exactly the same before.

**Review by marcelofrare — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Indeed you can't change dependencies on the middle of a stable version, and more with such heavy ones like full `libreoffice`. Do it in an extra module that adds such dependencies.

**Comment by primes2h** [comment]
I agree that this nice feature should be in a separate module. 
It works on Linux system only, so it would restrict the scope of use of the original module.

**Review by ruben-tonetto — APPROVED** [review]
Ok

**Comment by dcorio** [comment]
Please, put this in a separate module. Those deps cannot be installed everywhere (eg: odoo.sh?)

**Comment by andreampiovesana** [comment]
close for new version

**Pull request closed without merging**
