### PR TITLE
[14.0][MIG] base_comment_template

### PR DESCRIPTION
**Pull request by SimoneVagile**
Migration from 12.0 version [https://github.com/OCA/account-invoice-reporting/tree/12.0/base_comment_template](https://github.com/OCA/account-invoice-reporting/tree/12.0/base_comment_template).

**Note:** There's still an open PR, with unresolved comment and change requests for 13.0 [https://github.com/OCA/reporting-engine/pull/417](https://github.com/OCA/reporting-engine/pull/417).

### CODE REVIEW

**Review by petrus-v — CHANGES_REQUESTED** [review]
I was expecting only only base_commet_template to be migrated by this PR did you add extra files by errors ?

Has you have seen earlier, i've already migrate base_comment_template module ([in the wrong repo, sorry about that](https://github.com/OCA/account-invoice-reporting/pull/163)).
Where I've added some unit test to get good coverage on that base module [base_comment_template/tests/test_base_comment_template.py](https://github.com/OCA/account-invoice-reporting/pull/163/files?file-filters%5B%5D=.py#diff-1d4eaf2e78981c2c0771bdd2f99ee0cb862448ab72dcf278d2b912cf26e7f455). Could you bring those tests as well ?

**Comment by petrus-v** [comment]
Hi @SimoneVagile do you want that I move this PR https://github.com/OCA/account-invoice-reporting/pull/163 against this current repo ?

**Comment by SimoneVagile** [comment]
> Hi @SimoneVagile do you want that I move this PR [OCA/account-invoice-reporting#163](https://github.com/OCA/account-invoice-reporting/pull/163) against this current repo ?

@petrus-v Ok, can I ask you how did you move that branch in other repo preserving commit history? I tried, but I failed....

Please paste commands because I don't see anything on migrations documents.

**Comment by petrus-v** [comment]
@SimoneVagile [I've followed the same instructions as migration process](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0) by referencing account-invoice-reporting repo as remote, some thing like this:

```bash
git clone https://github.com/OCA/reporting-engine/ -b 14.0
cd reporting-engine
git remote add account_invoice_reporting git@github.com:petrus-v/account-invoice-reporting
git fetch account_invoice_reporting
git format-patch --keep-subject --stdout origin/14.0..account_invoice_reporting/14.0-mig-base_comment_template -- base_comment_template | git am -3 --keep
```

regards

**Pull request closed without merging**
