### PR TITLE
[15.0][MIG] sql_request_abstract

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v15.
Module moved from server-tools.
@JoanMForgeFlow
@lmignon could you take a look and if you think it's okay merge it? Thank you!

### CODE REVIEW

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM! Thanks

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi.

This module ``sql_request_abstract`` is shared between many modules : 
- ``bi_sql_editor`` (in reporting-engine)
- ``sql_export`` and co (in server-tools)

so, 2 options : 
- leave ``sql_request_abstract`` in server-tools
- move also ``sql_export`` & co in reporting-engine. (that case, please add a section in the ROADMAP.rst section of last revision of the related modules).

otherwise, that move makes no senses.

What do you think ?

LGTM Otherwise. Thanks for porting this module.

Note : Why oca-bot didn't ping me with a message like "A module you are maintaining has been modified" ?

**Comment by mariadforgeflow** [comment]
> Hi.
> 
> This module `sql_request_abstract` is shared between many modules :
> 
> * `bi_sql_editor` (in reporting-engine)
> * `sql_export` and co (in server-tools)
> 
> so, 2 options :
> 
> * leave `sql_request_abstract` in server-tools
> * move also `sql_export` & co in reporting-engine. (that case, please add a section in the ROADMAP.rst section of last revision of the related modules).
> 
> otherwise, that move makes no senses.
> 
> What do you think ?
> 
> LGTM Otherwise. Thanks for porting this module.
> 
> Note : Why oca-bot didn't ping me with a message like "A module you are maintaining has been modified" ?

Hi! I moved it from server-tools because in this module Roadmap in v14 said so: "Move modules sql_request_abstract and sql_export to oca/reporting-engine for version 15". I will now move sql_export also:)

BTW what do you exactly mean with "please add a section in the ROADMAP.rst section of last revision of the related modules)."?

Thank you!

**Review by legalsylvain — APPROVED** [review]
> I will now move sql_export also:)

> BTW what do you exactly mean with "please add a section in the ROADMAP.rst section of last revision of the related modules)."?

I didn't know you has planned to move also ``sql_export``. If you move it, all is OK, and you don't to add any text in the roadmap section.

kind regards.

**Comment by legalsylvain** [comment]
Hi maintainers, could you approve workflow ?
thanks.

**Comment by LoisRForgeFlow** [comment]
> Note : Why oca-bot didn't ping me with a message like "A module you are maintaining has been modified" ?

That is a nice question, it was a nice feature, but it's been a while since the last message of that kind I saw.

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM :+1:

**Comment by LoisRForgeFlow** [comment]
> > Note : Why oca-bot didn't ping me with a message like "A module you are maintaining has been modified" ?
> 
> That is a nice question, it was a nice feature, but it's been a while since the last message of that kind I saw.

Hi @sbidoul, hope you can help us with two doubts. 

1. The first one is above, why there is no maintainer mentions from the bot anymore?
2. The merge failed due to the cache of the pre-commit job (https://github.com/OCA/reporting-engine/runs/4405605005?check_suite_focus=true), this is not the first time I see this problem. Is there a way to easily invalidate the cache to solve this problem?

**Pull request merged**
