### PR TITLE
[FIX] If this is not a py3o report, do nothing at all

### PR DESCRIPTION
**Pull request by SimoRubi**
In some cases the UI remains blocked otherwise

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Review by tafaRU — APPROVED** [review]

**Review by eLBati — APPROVED** [review]

**Comment by SimoRubi** [comment]
@OCA/reporting-engine-maintainers can we merge this please?
Thanks

**Review by hurrinico — APPROVED** [review]
👍

**Comment by pedrobaeza** [comment]
Please change module version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

**Comment by SimoRubi** [comment]
@pedrobaeza done!

**Comment by SimoRubi** [comment]
@OCA/reporting-engine-maintainers is this ok to be merged?
Thanks

**Pull request merged**
