### PR TITLE
[16.0][MIG] report_xlsx_helper: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
#653

### CODE REVIEW

**Comment by baimont** [comment]
Hi @RodrigoBM,
Thanks for this pr.

Can you fix red pre-commit and add report_xlsx to test-requirements.txt to fix runboat and tests?

Inspiration can be found there : https://github.com/OCA/queue/pull/461/commits/33cf163f461b938588307f4d57aca1c339f6e96a

Thanks!

**Review by baimont — APPROVED** [review]

**Comment by RodrigoBM** [comment]
Hi @baimont 

I hope this is OK now. But I don't know why the "tests / Detect unreleased dependencies (pull_request)" doesn't work.

Regards

**Comment by baimont** [comment]
> Hi @baimont
> 
> I hope this is OK now. But I don't know why the "tests / Detect unreleased dependencies (pull_request)" doesn't work.
> 
> Regards

Hi @RodrigoBM 
Thanks for your changes.
This is normal. 
tests / Detect unreleased dependencies is there to remind you you'll have to remove the last commit once your dependency is merged.

**Comment by RodrigoBM** [comment]
Okey, 
Thanks @baimont

**Review by FernandoRomera — APPROVED** [review]

**Pull request merged**
