### PR TITLE
[14.0][MIG] bi_sql_editor

### PR DESCRIPTION
**Pull request by davejames**
migration to v14

Also includes the functionality to choose a group operator for each field. This functionality was originally written as a seperate module [bi_sql_editor_aggregate](https://github.com/OCA/reporting-engine/tree/12.0/bi_sql_editor_aggregate) for version 12 because upgrading existing databases was problematic, however as this is a fresh migration the same problem will not apply so it is included in the base module.

### CODE REVIEW

**Review by richard-willdooit — APPROVED** [review]
@davejames 

Looks complete, to me.

**Comment by legalsylvain** [comment]
Hi @davejames

First thanks a lot for porting this module. could you include some improvement done on V12 and that are not merged, by cherry pick ? 
- https://github.com/OCA/reporting-engine/pull/413  (Improve bi_sql_editor adding a new field computed_action_context that compute the context of the action, based on the custom action_context defined AND regarding the lines.)
- https://github.com/OCA/reporting-engine/pull/455 (refresh correctly the name of the action)
- https://github.com/OCA/reporting-engine/pull/496 (trivial refactoring, related to OCA/server-tools#2061)
- https://github.com/OCA/reporting-engine/pull/519 (conserve cron values when resetting to draft materialized views)

thanks !

**Comment by davejames** [comment]
Hi @legalsylvain 

I have cherry-picked 3 out of the 4, however #496 depends on changes in https://github.com/OCA/server-tools/pull/2061 which are not yet merged, let alone ported to 14.0. So I have excluded that one for now. I suggest we open a new PR for it once it is merged and ported to 14.0

**Comment by legalsylvain** [comment]
Hi @davejames. Thanks for cherry picking. 
I ported OCA/server-tools#2061 here https://github.com/OCA/server-tools/pull/2103.
When it will be merged, I'll do a little PR to add it.

thanks for porting this module !

**Comment by davejames** [comment]
@legalsylvain would it be possible for you to review/merge?

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
