### PR TITLE
[IMP] bi_view_editor: Restrict access to BI View Editor Managers

### PR DESCRIPTION
**Pull request by yankinmax**
Forward-port changes from 15.0:
- [x] https://github.com/OCA/reporting-engine/pull/801

### CODE REVIEW

**Comment by yankinmax** [comment]
@ivantodorovich @HviorForgeFlow @legalsylvain can you pls take a look?

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Review by jcoux — APPROVED** [review]

**Comment by yankinmax** [comment]
@HviorForgeFlow let's merge? and great thanks for handling that

**Pull request merged**
