### PR TITLE
Update from template

### PR DESCRIPTION
**Pull request by etobella**

### CODE REVIEW

**Comment by etobella** [comment]
@PabloEForgeFlow I took the commit from #714 in order to finish the change :smile:

**Comment by PabloEForgeFlow** [comment]
@etobella I didn't know where to begin fixing that travis pipeline, so thanks a bunch! I'm not really familiar with OCA code, so I don't know if I'll be of any help, but do let me know if I you need anything.

**Comment by PabloEForgeFlow** [comment]
Testing locally I found that `graphviz` is missing from the `bi_view_editor` manifest. This ought to fix the pipeline:
```python
    'external_dependencies': {
        'python': ['pydot'],
        'deb': ['graphviz']
    },
```

**Comment by etobella** [comment]
Thanks @PabloEForgeFlow 

/ocabot merge patch

**Pull request merged**
