### PR TITLE
[12.0][report_xlsx_helper] fix error message

### PR DESCRIPTION
**Pull request by ivantodorovich**

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Ping @luc-demeyer

**Comment by luc-demeyer** [comment]
@ivantodorovich 
Thanks for this contribution.

some feedback:

1)  commit 4da65fc is already  part of PR https://github.com/OCA/reporting-engine/pull/311 hence I think it's best that you review & approve PR 311 so that we can move forward on that one.

2) commit 4f93c2c  should be kept. 
I propose that you rework this PR to only keep this fix on the error message (which I will approve so that we can merge).

**Comment by ivantodorovich** [comment]
Hi @luc-demeyer !
Thanks for reviewing this and sorry for not replying before

It's done :+1:

**Review by luc-demeyer — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
