### PR TITLE
[FIX] bi_sql_editor: solves the update all break

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR updates the readme of bi_sql_editor to inform how to solve the update all break.

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by JordiBForgeFlow — APPROVED** [review]
Tested in a broken environment, and fixes the issue. Works like a charm!

**Comment by MiquelRForgeFlow** [comment]
NOTE: For reference, added here the error that this PR solves.

> Selection_632
> in https://github.com/OCA/reporting-engine/pull/264#issuecomment-470890648

**Comment by legalsylvain** [comment]
Hum. Thanks for the comment. 

My question is : I use this module since years (version 8 and 12), and I realize update all each month. I never faced that issue. 
Do you know in which context ?

**Comment by MiquelRForgeFlow** [comment]
I don't remember. Perhaps it has to do if you have bi sql views for materialized views, not sure. @HviorForgeFlow do you remember?

**Comment by legalsylvain** [comment]
(I only use materialized views).

**Comment by legalsylvain** [comment]
Well, I removed that comment in #670 as it seems to work. If there is a problem, we could always add it again, with a more detailled text of what the --load solves.

thanks for your answers.

**Pull request merged**
