### PR TITLE
[16.0] [MIG] base_comment_template

### PR DESCRIPTION
**Pull request by AMhadhbi**

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I actually only do functional testing and this module is just the base module, but I checked in runboat that I can see the views:
* tree view of comments in partner form view
* menu for all comments here: settings > technical > reporting > comment templates

Of course, I could not create a comment template because we need account_comment_template (https://github.com/OCA/account-invoice-reporting/pull/242) or sale_comment_template or a similiar extension.
I will test those after this module is merged. :)

Can someone do a code review too?

**Review by chandni299 — APPROVED** [review]

**Comment by marylla** [comment]
@pedrobaeza Hi Pedro, can you merge this PR please?

**Pull request merged**
