### PR TITLE
[MIG] report_qweb_parameter: Migration to 12.0

### PR DESCRIPTION
**Pull request by julianram**
Preserved commit history

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1: Just squash your last commit please!

**Comment by jarroyomorales** [comment]
ping @etobella

**Review by etobella — APPROVED** [review]
LGTM :+1: 
Attend @jarroyomorales comments and all will be perfect :smile: 
@pedrobaeza should we superseed #281 for this PR?

**Pull request merged**
