### PR TITLE
[16.0][ADD] sql_export_delta

### PR DESCRIPTION
**Pull request by hbrunn**
This module extends the functionality of ``sql_export`` to allow you to
only export changes between export runs.

I added a [second commit](https://github.com/OCA/reporting-engine/pull/873/commits/0e13eda3b1b4d6790514e20fd6d0ca5cf34380c7) that allows users to keep the results of an sql export, that's useful independently of deltas, and very useful with deltas.

### CODE REVIEW

**Comment by Stephanvandenberg** [comment]
Hi participants,

I was trying this functionality but see there is a merge conflict. Will that be resolved?

**Comment by legalsylvain** [comment]
@hbrunn could you rebase ?

**Comment by hbrunn** [comment]
@Stephanvandenberg @legalsylvain thanks for the headsup, rebased and resolved conflicts

**Review by legalsylvain — APPROVED** [review]
Code review. LGTM.

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
