### PR TITLE
[WIP] report_py3o and report_py3o_fusion_server Odoo 13 Migration

### PR DESCRIPTION
**Pull request by dupski**
Makes `report_py3o` and `report_py3o_fusion_server` work with Odoo 13 (community)

* Now working :)

TODO:

* Update / Add Tests?
* Update to meet OCA [Guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by lmignon** [comment]
@dupski Thank you for the migration. Do you plan to finish this work? If not I'll redo the complete process to preserve the history since I need these addons.

**Comment by lmignon** [comment]
@dupski I've redo all the migration process to preserve the history and fix remaining issues. In the same time I preserved your commit  9c67c97 to give you credits into the migration process. I propose to close this one in favor of #347 
Thank you for your work!

**Comment by dupski** [comment]
Hi @lmignon thanks very much for that! The priority for me was getting it working and I've not had time since to revisit and finish this properly.

I am now a member of the OCA and am aware of the instructions so I will make sure I do the next one correctly :)

**Comment by lmignon** [comment]
You're welcome @dupski ! no stress :smirk:

**Pull request closed without merging**
