### PR TITLE
[MIG][11.0] report_py3o

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**

### CODE REVIEW

**Comment by lmignon** [comment]
@vincent-hatakeyama The migration is already done here #285 Can you take a look at this PR and review it to finalize it?

**Comment by vincent-hatakeyama** [comment]
This migration is working, we have tested it. My company also created the module.

**Comment by lmignon** [comment]
@vincent-hatakeyama Which migration? Is it #285?

**Comment by vincent-hatakeyama** [comment]
What we have tested is this PR.

**Comment by lmignon** [comment]
Sorry but the PR #285 was there before this one and is working fine (except an issue to solve with the image tag). We only need some more reviews to merge-it. Can you test it so we can move forward and finalyse the migration?

**Pull request closed without merging**
