### PR TITLE
[ADD] report_qweb_pdf_watermark

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As always bringing excellent generic features. Remember to add the lines for the display in .travis.yml file.

**Comment by hbrunn** [comment]
weird that we need the x server, but let's see how it works now. And thanks for the flowers ;-)

**Comment by hbrunn** [comment]
does anyone have a clue how to get a statically built wkhtmltopdf with pachted qt on runbot?

**Comment by hbrunn** [comment]
@moylop260 @gurneyalex is this some runbot docker glitch or did I mess up something?

**Comment by moylop260** [comment]
@hbrunn sorry man is a runbot issue WIP from https://github.com/OCA/runbot-addons/issues/111

**Comment by hbrunn** [comment]
good to know, thanks

**Comment by lfreeke** [comment]
:+1: (test)

**Comment by pedrobaeza** [comment]
Do you know why Travis is red?

**Comment by hbrunn** [comment]
@pedrobaeza because of https://github.com/OCA/reporting-engine/pull/86#issuecomment-265598246 - I wouldn't know how to fix this without travis CI admin permissions...

**Comment by pedrobaeza** [comment]
Ouch, no clue either. Maybe write to Travis to say if they can provide any QT patched version?

**Comment by moylop260** [comment]
FYI the following https://github.com/OCA/maintainer-quality-tools/pull/406 help us to install webkit-patched from custom BINARY PATH: `${HOME}/maintainer-quality-tools/travis`

**Comment by hbrunn** [comment]
restarted travis to see if the magic works

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
