### PR TITLE
IMP add colors constant for xlsx format

### PR DESCRIPTION
**Pull request by bealdav**
Xlsx writer don't provide documentation about available colors.

This PR add a constant of colors available

Tested with Libreoffice
test

Download full file here
[colors.xlsx](https://github.com/OCA/reporting-engine/files/983314/colors.xlsx)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this information in the xlsxwriter library?

**Comment by bealdav** [comment]
No, this information is not in the library. Then I had to experiment it.
It can be useful for other users of the lib

**Comment by bealdav** [comment]
ping @adrienpeiffer

**Comment by bealdav** [comment]
just found in the doc, sorry

**Pull request closed without merging**
