### PR TITLE
[FIX] report_qweb_signer: noupdate defaults

### PR DESCRIPTION
**Pull request by chienandalu**
We don't want our custom parameters be reset every time the module
updates.

cc @Tecnativa TT32256

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
True, but you need a migration script for existing databases changing such flag.

**Review by carlosdauden — APPROVED** [review]
Create migration script

**Comment by chienandalu** [comment]
Added migration script

**Comment by sbidoul** [comment]
@ThomasBinsfeld

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I suppose this should be fw-ported to v13.

**Comment by chienandalu** [comment]
Forwarded to #543

**Pull request merged**
