### PR TITLE
[13.0][MIG] report_async

### PR DESCRIPTION
**Pull request by Saran440**
Standard Migration

### CODE REVIEW

**Comment by atchuthan** [comment]
@Saran440 Please resolve the conflicts

Conflicting files
oca_dependencies.txt

**Comment by newtratip** [comment]
> @Saran440 Please resolve the conflicts
> 
> Conflicting files oca_dependencies.txt

@atchuthan Resolved, Could you check and approve this ?

**Review by atchuthan — APPROVED** [review]

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :+1:

**Comment by kittiu** [comment]
@HviorForgeFlow can this one merged too?

**Pull request merged**
