### PR TITLE
[14.0][FIX] report_xlsx : safe_eval object time

### PR DESCRIPTION
**Pull request by Saran440**
error when condition `report.print_report_name and not len(docids) > 1`
time object should be `time.time()`

Selection_001

### CODE REVIEW

**Comment by kittiu** [comment]
What about this? Core odoo is using it.
https://github.com/odoo/odoo/blob/14.0/addons/web/controllers/main.py#L41

**Comment by mourad-ehm** [comment]
In v 14.0 time module is already in safe_eval https://github.com/odoo/odoo/blob/14.0/odoo/tools/safe_eval.py#L38
look at this https://github.com/OCA/reporting-engine/pull/445/commits/ec4a6ad6ec8249549afc4b82fa28e5fb538ceb20

**Comment by Saran440** [comment]
@kittiu @mourad-ehm Fixed. Thank you for your advise :)

**Review by kittiu — APPROVED** [review]

**Review by newtratip — APPROVED** [review]
Code Reviewed.

**Comment by newtratip** [comment]
@OCA/tools-maintainers Could you merge this ?

**Review by etobella — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Pull request merged**
