### PR TITLE
[15.0][MIG] bi_sql_editor

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard migration to v15
@ForgeFlow

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi. thanks for porting this module : 
- could you take a look on pre-commit errors ? (regarding runbot, I think that it should be removed, and replaced by runboat...)
- could you add a key in the manifest files ? ``'maintainers' = ['legalsylvain']``. The option was not available when I published the module to the OCA.

thanks.

**Review by legalsylvain — APPROVED** [review]
thanks.

**Comment by legalsylvain** [comment]
@mariadforgeflow. I'd like to introduce some changes / improvement / refactoring on that module.

What do you prefer. do you want I make PR against your PR, or do you prefer we merge the current one, and then I propose improvment ?

thanks.

**Comment by mariadforgeflow** [comment]
@legalsylvain if you want to add some improvements I think it makes more sense if we first merge this PR and then you create a new [IMP] PR. So I think we could merge this one if it's okay for you:)

**Comment by legalsylvain** [comment]
Ok ! I'll ping you for the review. 
Note : 
- some improvment will requires to update the installed modules.
- I dont' have right to merge this PR.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  runbotat tests

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM!

**Comment by yankinmax** [comment]
@mariadforgeflow Is it ready to be merged? Can I help?

**Comment by mariadforgeflow** [comment]
@yankinmax yes it is ready! 
@pedrobaeza Hi! Could you please merge this? Thank you in advance.

**Comment by pedrobaeza** [comment]
OK, merging trusting in the reviewers:

/ocabot migration bi_sql_editor
/ocabot merge nobump

**Comment by CasVissers-360ERP** [comment]
@mariadforgeflow 
I think you made a typo while migrating the module:
 `  index_name = fields.Char(ompute="_compute_index_name")`

**Comment by mariadforgeflow** [comment]
@CasVissers-360ERP thanks!! Fixed in https://github.com/OCA/reporting-engine/pull/583.

**Comment by legalsylvain** [comment]
Hi @mariadforgeflow. I'm currently migrating ``bi_sql_editor`` in V16. (see : https://github.com/OCA/reporting-engine/pull/670)

I don't understand why you introduced that text in V15 : 
```
* You must put this module as `server_wide_modules` in your odoo configuration file
  or add '--load=bi_sql_editor' if you start odoo in command line.
```

could you provide precision ? At my side, I never set that settings and it works.

thanks !

**Comment by mariadforgeflow** [comment]
Hi @legalsylvain! I didn't introduce this text, it was already there in v14 when I migrated the module. 
I checked and it was added here: https://github.com/OCA/reporting-engine/commit/bf96a356021beb2986c5223377e261e900ef2ecd

I never start odoo in command line so I don't know about this, sorry.

**Comment by legalsylvain** [comment]
Thanks for your answer. @davejames : could you help me on that topic ? 

(Ref : https://github.com/OCA/reporting-engine/pull/518)

thanks !

**Comment by davejames** [comment]
@legalsylvain i'm not sure, this was only committed by me during the migration, originally this was authored by @MiquelRForgeFlow

**Comment by legalsylvain** [comment]
;-) !
OK ! @MiquelRForgeFlow : any idea ?

**Comment by MiquelRForgeFlow** [comment]
@legalsylvain was added in https://github.com/OCA/reporting-engine/pull/269 (see https://github.com/OCA/reporting-engine/pull/269#issuecomment-1292071296).

**Pull request merged**
