### PR TITLE
[16.0][IMP] base_comment_template: update readme files

### PR DESCRIPTION
**Pull request by alan196**
Change deprecated t-raw to t-out.
Rename invoice_comment_template to account_comment_template

I have updated the readme files and run oca-gen-addon-readme

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@alan196 can you rebase and fix the conflicts?

**Comment by alan196** [comment]
@gurneyalex I rebased the branch :+1:

**Review by ivantodorovich — APPROVED** [review]
This one looks ready to merge 👍🏻

**Comment by pedrobaeza** [comment]
It has conflicts. Can you please rebase and fix it?

**Comment by alan196** [comment]
I have rebased and fixed the conflicts @pedrobaeza @gurneyalex

**Pull request merged**
