### PR TITLE
[MIG] Migrate report_xls to v9.0

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Excel report engine
===================

This module adds Excel export capabilities to the standard odoo reporting
engine.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Why migrate? https://github.com/OCA/reporting-engine/tree/9.0/report_xlsx already exists

**Comment by MiquelRForgeFlow** [comment]
But this module you mention is another different module. XLS != XLSX

**Comment by JordiBForgeFlow** [comment]
In v9 we should only use XLSX. 

XLS is very old

**Comment by StefanRijnhart** [comment]
I see the rationale for this (the mrp bom structure module port) was also migrated to xlsx, so closing this.

**Pull request closed without merging**
